### ISSUE TITLE
rpi3 + node-red

### ISSUE THREAD

**Issue by eugenner** [TotallyInformation/node-red-contrib-uibuilder#1]
Node-RED 0.17.5
Raspberry Pi 3 (2017-04-10-raspbian-jessie.img)

After uibuilder was installed, I tried to add uibuilder node to a flow and that was worked. But link http://localhost:1880/uibuilder is not worked. And as I see there are no folder created (~/.node-red/uibuilder). And in the console of node-red I have got message:

17 Aug 16:32:46 - [error] [uibuilder:fe60770c.b02be] TypeError: Cannot read property 'userVendorPackages' of undefined

**Comment by TotallyInformation** [comment]
Hi, have you perhaps changed other settings so that your root URL is no longer "/"?

If you have changed httpNodeRoot or httpRoot, you will need to put the appropriate prefix before. e.g. if httpNodeRoot = "/mypath", your uibuilder url would be "/mypath/uibuilder".

Also check that you haven't changed the URL in the node properties.

**Comment by TotallyInformation** [comment]
As a quick test, could you try adding the following to your settings.js

````
    uibuilder: {
        userVendorPackages: ['riot']
    }
````

You can use something else other than riot if you like or can use an empty array.

**Comment by eugenner** [comment]
Thanks for answer!

No, I just tried to start from default settings. I installed node-red and uibuilder node type. After that I put uibuilder node in the editor, deployed it and after tried this link http://127.0.0.1:1880/uibuilder <http://127.0.0.1:1880/uibuilder>, and got error in browser: Cannot GET /uibuilder


After that I checked path for files and there were no folders for uibuilder. And did the same not only on rpi, but on a macbook too. Got the same result.

**Comment by eugenner** [comment]
Ok, I added this uibuilder attribute to module.exports in mine settings.js (btw I don’t know exactly how to do that properly). But seems that nothing changed.

**Comment by TotallyInformation** [comment]
OK, bear with me for a bit while I create a clean environment and test.

**Comment by eugenner** [comment]
Ok and one moment, now I see that there no error messages in the node-red console output about userVendorPackages.

**Comment by TotallyInformation** [comment]
OK, I've reproduced. Let me do some digging.

**Comment by TotallyInformation** [comment]
Right, I have a fix. Will publish now. Give it a few minutes and check for a new version.

**Comment by TotallyInformation** [comment]
Took slightly longer than expected but should be fixed now.

**Comment by eugenner** [comment]
Thanks, I will try to check it.
