### ISSUE TITLE
this protocol check may be https:

### ISSUE THREAD

**Issue by PterX** [TotallyInformation/node-red-contrib-uibuilder#100]
https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/926e2a495b746aee003f56c182eed0ec32f5d639/nodes/uibuilder.html#L634

like this

```
if (window.location.protocol !== 'https:') {
```

I have test at my service

**Comment by TotallyInformation** [comment]
Hi, thanks for that. I will test and release an update.

**Comment by TotallyInformation** [comment]
Fix is in v3.0.1 about to be released.
