### ISSUE TITLE
Extra fiels

### ISSUE THREAD

**Issue by eduardjdejong** [TotallyInformation/node-red-contrib-uibuilder#101]
Hi,

I am using Uibuilder and it's amazing really. But I was wondering to edit extra field via the injectnode for a Apex chart line, bar chart and sparkline like:

Chart Line
- seriesname

Donut: 
- TitleText
- Labels

But I lack some knowlegde for this. The code for the message I use is

      uibuilder.onChange('msg', function (msg) {
            Vue.set(vueApp.series, 0, {'data': msg.payload[0].date})
            //vueApp.series[0].data = msg.payload
            console.log('SERIES: ', vueApp.series)
        })

My Injectpayload is :

{
        "name": "series-1111",
        "data": [
            [
                1582672682720,
                4
            ],
            [
                1582672743197,
                8
            ]
        ]
}

I am unable to change the name when I use  Vue.set(vueApp.series, 0, {'name': msg.payload[0].name}). Do you have an example to edit the seriesname and the donut and/or sparkline items perhaps?

Kind regards

Eduard

**Comment by TotallyInformation** [comment]
This appears to be more of a VueJS question than a uibuilder one? 

While I certainly use VueJS, I can't by any means claim to be an expert. You may get more joy from the VueJS forum or even from the Node-RED forum. I'd like to help further but I'm afraid I am knee-deep in other things just now and don't really have time to dedicate to working out this Vue/Apex question - sorry about that.

You can, of course, take uibuilder out of the equation while you sort out the correct Vue function. I sometimes use a `setTimout` function with a delay of a few seconds in the `mounted` section of the js file to simulate a message from Node-RED. All you need to do then is reload the page.
