### ISSUE TITLE
v3.x is silently broken on Firefox - buttons unresponsive and no modal dialogs (Windows 10, 64-bit)

### ISSUE THREAD

**Issue by alastaira** [TotallyInformation/node-red-contrib-uibuilder#125]
I've just spent some time struggling with upgrading from a v2.x instance to the latest v3.2.1.  I'd read all the upgrade notes, the fact that there were breaking changes, that Vue.js was no longer included in installation etc., but it basically seemed completely borked - when I edited a uibuilder node in an existing flow, neither the "Edit Files" not "Manage front-end libraries" buttons did anything at all (no errors were logged either). If I went to the /uibuilder url, I just got a blank screen.
I tried uninstalling and reinstalling, with no improvement.

As something of a last resort, I decided to open the node-red flow editor in Google Chrome instead, when I suddenly saw what I was missing!
Firstly, the "WARNING The selected uibuilder template (vue) is MISSING the following dependencies: vue, bootstrap-vue" modal dialog window. And then the ability to install packages from the built-in library manager (which, once working, was blissfully simple). For some reason, neither of these appear in Firefox 86.0.1 (64-bit) under Windows 10.

**Comment by TotallyInformation** [comment]
OK, I've tried Node-RED and uibuilder in Firefox and it is all working just fine.

What I think may have happened is something I've seen with other web apps in the past, the browser occasionally fails to update all of the required libraries and ends up in an odd state. Generally, the first thing to do is to test the site using an Private browsing session (which always has a clean cache). If that works, then you can usually fix things in your main session by doing <kbd>ctrl</kbd>-<kbd>F5</kbd> a couple of times to get the browser to forcibly reset all of its cache. If that still doesn't work, you may need to clear the cache and history from the browser.
