### ISSUE TITLE
Uibuilder Security does not turn on, even though TLS is active

### ISSUE THREAD

**Issue by amitsinghio** [TotallyInformation/node-red-contrib-uibuilder#126]
Hi,

I am currently struggling with activating uibuilder's new security feature in production, even though TLS is activated. In dev mode it turns on fine (but cannot require the security.js). There is a nginx configured with the same options as in the wiki. The same checks you do, when checking the security checkbox, work perfectly fine in the developer tool's console (window.location.protocol returns "https:").

Any help is appreciated. Thanks in advance.

best regards,

Amit Singh

**Comment by TotallyInformation** [comment]
Hi Amit, I think this is because you are using NGINX for the TLS termination so uibuilder in the Editor thinks you haven't turned it on?

That is my bad because I should have allowed for that I think. I am probably going to have to back off the settings slightly so that you only get a warning in production mode as well.

As a work around, you can run Node-RED in development mode and you should only get a warning.

**Comment by amitsinghio** [comment]
Hey,

I still don't get, why you're checks don't succeed, because node-red is using ssl as well as nginx. So in theory there is no way windows.location.protocol can deliver anything other than https, which your check is based on right? Or is there any other check you do to prevent turning security on.

best regards,

Amit Singh

**Comment by TotallyInformation** [comment]
Urm, OK, yes you are right. As far as I can remember that is the only check. But I'll have to go through the code to make sure. I'll see if I can find some time to review it. There are clearly some oddities happening.

**Comment by TotallyInformation** [comment]
In case anyone else is looking at this, the ongoing discussion is here: https://discourse.nodered.org/t/uibuilder-security-js/44214

That thread also has a working example.

**Comment by TotallyInformation** [comment]
Fixed in next release.

**Comment by TotallyInformation** [comment]
If you want to try the fix, please install the "express" branch direct from GitHub.
