### ISSUE TITLE
Support import statements

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-uibuilder#129]
Looking at various vue libraries they all show usage with `import` statements. For example https://github.com/skalinichev/uplot-wrappers has:
```
<script>
    import Vue from 'vue';
    import uPlot from 'uplot';
    import UplotVue from 'uplot-vue';
    import 'uplot/dist/uPlot.min.css';

    const Chart = Vue.extend({components: {uplotvue: UplotVue}});
 </script>
```
I don't know whether it's at all possible to support this stuff in uibuilder or whether it's already possible, but it sure would be nice. As it is, one has to install the npm module and then manually track down which files need to be loaded directly from the html. IMHO sorting this out should be higher priority than some of the editor improvements listed on the projects page, but that's just me :-).

**Comment by TotallyInformation** [comment]
Import statements are not natively supported in JavaScript unless you are using modern components.

They only work if you use a build step.
