### ISSUE TITLE
uibuilderfe's global nature cause hot-reload issues

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-uibuilder#134]
I'm having issues with Vue's hot reload when using vue-cli-service and uibuilderfe. Specifically, uibuilder is global and never reloaded/restarted by the hot-reload (well, except in the infrequent situations where hot-reload decides it really has to do a full page reload).
I'm calling uibuilder from the main Vue component, that's also where the onChange callback lives. If I edit this component, Vue will reload it, which leads to a good deal of confusion. First, if the component blindly calls onChange in its mount action then there will be two onChange handlers: the old one from the "dead" component and the new one. I then added some smarts not to start a second onChange but that doesn't work either 'cause the old one updates the wrong variables... I can hack some more around this but as far as I can tell the ideal situation would be for uibuilder to:
- allow finding out whether it's started so main can decide whether it needs to start uibuilder or not
- provide some way to reinit uibuilder so it can be linked to the new main component and a fresh onChange handler can be registered without having the old one still around

There are a bunch of different variations possible on this...

**Comment by TotallyInformation** [comment]
Would it be better for the `uibuilder.start()` function to set an internal flag? It could then make sure it wasn't run twice?

Not sure that helps the onChange issue though.

I don't think that it is possible for uibuilderfe to be reinitialised completely. However, I could probably add a function to remove all onChange listeners. All that onChange does is push a new array element onto `self.events`. That object is hidden from access but I can easily add a `clearEventListeners` function that you can call if Vue is being reinitialised.

Thoughts?
