### ISSUE TITLE
eslint errors

### ISSUE THREAD

**Issue by tve** [TotallyInformation/node-red-contrib-uibuilder#135]
Dunno whether you care, but eslint is throwing errors on uibuilderfe.js and I'm having to exclude that file:
```
     1:11   error  'Vue' is defined but never used                                            no-unused-vars
   282:30   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   344:54   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   349:53   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   381:38   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
   705:34   error  Do not access Object.prototype method 'hasOwnProperty' from target object  no-prototype-builtins
  1026:33   error  Empty block statement                                                      no-empty
  1314:106  error  Empty block statement                                                      no-empty
  1315:76   error  Empty block statement                                                      no-empty
  1316:72   error  Empty block statement                                                      no-empty
```
If you don't care, just close the issue. Thanks!

**Comment by TotallyInformation** [comment]
Hi, thanks for this. I thought that I'd killed off all of the hasOwnProperty issues with the last update, I'll double check. I think that the no-empty are rather spurious but again, I'll check.

By the way, I was checking out https://esbuild.github.io/ earlier and that looks pretty good. With the newly refactored code, I'm thinking I might actually be able to build in esbuild as an option that could be pre-configured for front-end code. But it could also be used to get the back-end code more efficient.

**Comment by tve** [comment]
The no-empty are there so you put a comment inside the empty block, something like `/* empty */`, just to signal that this is not a refactoring error. Oh well...

**Comment by TotallyInformation** [comment]
Still continuing to improve the eslint stuff as I learn more. Not yet perfect but certainly improving. I'll keep at it.

I'll close this for now, thanks again for reporting. Watch out for v3.3.0 to go live any minute. You've been instrumental in some of the changes for this release so thanks again.
