### ISSUE TITLE
div "app" not displaying any video

### ISSUE THREAD

**Issue by ralbright-wa** [TotallyInformation/node-red-contrib-uibuilder#136]
Installed on a Intel NUC, with Ubuntu 20.04, getting an odd error in firefox.

When loading the UI Builder with the stock load from Node-REDscape [https://github.com/playfultechnology/node-redscape/wiki/Video-Overlay-(and-Video-Background)](url), when viewing on a different computer (not the Intel NUC, the app div shows up correctly, however on the computer running Node.Red, the app div does not fill in.

Enter the information as given at the link above (do need to add "Body {" to the CSS file, for whatever reason that is not on the page.)

When displayed on the computer running NodeRed, the inspect of the browser shows the following for the app div
`< div id="app" >
< !-- -- >
< /div >`

(spaces added to HTML tag so it would display here.)

However on any other computer viewing the same file, the app div does fill out correctly. Now the strange part.... if I change the id of the div tag to app2, then the div fills out properly (but does not give dynamic updates from NodeRed).

**Comment by ralbright-wa** [comment]
So it would appear that the cause of this is the < div v-if="msg.payload" > is not rendering.... As I put a < div v-else>Help< /div > and that does render and show but the <div with the v-if does not....

not sure how to fix this.

**Comment by TotallyInformation** [comment]
Sorry, thought that I had responded to this.

You cannot simply put `msg.payload` into the VueJS code, that doesn't work - not a uibuilder issue.

You need to pass the msg.payload to a VueJS variable that you declare in the VueJS app's data section ( the template index.js file has some entries already there to point the way ).
