### ISSUE TITLE
Change uibRoot directory

### ISSUE THREAD

**Issue by anxuae** [TotallyInformation/node-red-contrib-uibuilder#137]
Hello,

Is it possible to change the `uibRoot` directory to a custom sub-directories tree?

I'm using the project mode and I would like to put the `uibuilder` folder in a sub-directory. It could be nice if I can configure it in the `package.json` file. For instance:

```json
    "node-red": {
        "settings": {
            "flowFile": "flow.json",
            "credentialsFile": "flow_cred.json",
            "uibRoot": "path/to/uibuilder"
        }
    }
```

**Comment by TotallyInformation** [comment]
Hi Anxuae, thanks for raising. I'm going to move this to the discussions if that's OK. This issue will close but you should be notified about the discussion and be sent a link.
