### ISSUE TITLE
There lost uib parameter,null exception will happen

### ISSUE THREAD

**Issue by PterX** [TotallyInformation/node-red-contrib-uibuilder#144]
https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/03133a3e4f5051521cdf9531dae7779c087da36c/nodes/socket.js#L315

**Comment by TotallyInformation** [comment]
Please include sufficient information when raising issues. That is what the template is for. Including the version and the actual error produced really is needed if I'm going to track down any issues.
