### ISSUE TITLE
Webpack issues: take 2

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#15]
I have succeeded in using webpack to bundle everything up into the dist folder and run from there. The main issue is that because (I think) webpack puts everything into modules then if it is desired to include uibuilderfe.js in the bundle then it is necessary to copy it from the node into src and add to the end:
`if (typeof module === "object" && module.exports) {
  module.exports = uibuilder
}`
and at the start of index.js (and anywhere else uibuilder is referenced):
`if (typeof require != "undefined") {
  var builder = require('./uibuilderfe')
} else {
  var builder = uibuilder
}`
and then use builder as the handle to the uibuilder methods. It is not possible to use
`var uibuilder = require('./uibuilderfe')`
as that causes an error when running from src as uibuilder is declared const. If uibuilder is changed to declare uibuilder as a var rather than const then in index.js it is just necessary to have
`if (typeof require != "undefined") {
  var uibuilder = require('./uibuilderfe')
}`
and index.js can reference uibuilder as normal.
I don't know what is the best thing to do.

**Comment by TotallyInformation** [comment]
Could the extra code be put into uibuilderfe.js? That would certainly be preferable. If we could add some code there that works out whether it is being called directly or via webpack, perhaps all the issues could be resolved.

Maybe, when called via webpack, uibuilder needs to be an export but not when called directly?

**Comment by colinl** [comment]
The code declaring the exports can go at the end of uibuilderfe and does not cause problems, since when called directly module.exports is not defined. So I think that could just be added there without issue. Similarly the code at the start of index.js works whether used with webpack or not. The issue is that I think uibuilderfe needs to be in the src directory, at least I could not get webpack to pick it up from the node. There may be an incantation that would allow that however.

**Comment by TotallyInformation** [comment]
Updated as per other issue. Should now work.
