### ISSUE TITLE
Add CORS support to socket.io

### ISSUE THREAD

**Issue by anthonyma94** [TotallyInformation/node-red-contrib-uibuilder#153]
Hello,

I was hoping support for CORS would be added to socket.io.

I'm looking to develop an SPA using uibuilder, and it would be amazing to be able to run a local development server on my laptop while Node-RED is on the server. However, since CORS needs to be explicitly implemented for socket.io v3+, I lose all ability to communicate with the server without building my project every time I change something.

**Comment by TotallyInformation** [comment]
Hi Anthony, is there a reason you closed this? I do want to include sensible CORS settings but I did hit an issue previously. Do you have any recommendations of reasonable settings and would you see that CORS should be optional?

**Comment by anthonyma94** [comment]
I found out that I could set a `devProxy` to the Node-RED server for development, so for my use case at least I don't specifically need CORS. It would still be helpful for those who would like to host the project outside of Node-RED though.
