### ISSUE TITLE
sioMiddleware.js not running

### ISSUE THREAD

**Issue by dczysz** [TotallyInformation/node-red-contrib-uibuilder#159]
I'm having issues getting sioMiddleware.js to do anything.  I tried changing ~/.node-red/uibuilder/.config/sioMiddleware.js to the code below and am not seeing any error messages logged, either on the uibuilder front end or in node.

```js
// sioMiddleware.js
module.exports = function(socket, next) {
  next(new Error('test error from sioMiddleware'));
}
```

But if I populate sioUse.js with the same code I _do_ get an error as expected.

![image](https://user-images.githubusercontent.com/32844299/139493864-b0751e76-bf14-4638-a26c-69fd6dd57259.png)

And the following log shows up in `journalctl`
```
Oct 29 13:48:17 raspberrypi Node-RED[26714]: 29 Oct 13:48:17 - [error] [uibuilder:uibuilder] ERROR received, ID: BT65fYSyzTmopURXAAAC, Reason: test error from sioUse
```

Since this works fine with sioUse.js I'm not sure what I may be doing wrong with sioMiddleware.js.  Both files are in ~/.node-red/uibuilder/.config/, and I restarted Node-RED after each change.  For my use case, it makes more sense to use sioMiddleware than sioUse since I only want code to run on the initial connection, not every message.

### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 14.18.1
npm            | 6.14.15
Node-RED       | 2.1.3
uibuilder node | 4.1.4
uibuilderFE    | 4.1.1
OS             | Raspbian GNU/Linux 10 (buster)
Browser        | Firefox 93.0 (64-bit)

### How is Node-RED installed? Where is uibuilder installed?

Node-RED is installed using the provided script at https://raw.githubusercontent.com/node-red/linux-installers/master/deb/update-nodejs-and-nodered

uibuilder is installed through the Manage Palette to ~/.node-red/node_modules and uibuilder root ~/.node-red/uibuilder

**Comment by TotallyInformation** [comment]
Sorry I haven't replied to this before. 

Another area I need to look at. With sioUse, I'm not sure that sioMiddleware is needed now.

In fact, looking in `nodes/libs/socket.js` (line 168), I can see that it stopped working once I upgraded Socket.io past v2 - it was one of the breaking changes in Socket.IO v3.

You should just use sioUse which does the same thing but at a different level in the code - that you don't need to worry about :)

**Comment by TotallyInformation** [comment]
This has now been resolved in vNext if you'd care to try that out. I've also better documented the difference between the 2 middlewares - as I'd forgotten! You will find that in the Tech Docs.

**Comment by dczysz** [comment]
>sioUse which does the same thing

Almost!  My main goals are:
1. If user is unauthenticated (missing or invalid JWT cookie), redirect to /auth
2. When a user does something and a msg is received in NR, know which user it was

For # 1, I need access to a `request` object to get `request.headers.cookie`
For # 2, I need access to both `request.headers.cookie` and the `socket.id`

But sioUse only provides the `msg`, so I didn't have a way to access the cookie from that middleware.

My current workaround is similar to what I asked about here https://discourse.nodered.org/t/is-it-safe-to-use-the-uibuilder-route-for-a-node-red-based-http-in-api/55767.  When the frontend receives the `client connect` msg, it sends an http request to `/ui/api/connect`.  That route is handled by an http-in node in Node-RED.  When it receives the request, it reads the socket ID from the request body, and reads the cookie from the request headers.  Then it adds an entry to `global.sockets` in this format
```js
{
  socketId: { ...decoded JWT user data }
}
```
With that populated, I can look up the user any time a msg is received from the frontend, so I can control access based on their roles, log appropriately, etc.  Although this doesn't allow me to redirect an authenticated user to our auth page (# 1) like the old dashboard middleware (unless done from the frontend).  So my current solution is to provide basically a "read only" page when unauthenticated, and all interactions get blocked.

Is there a better way to do this that I may have missed?  It looked like sioMiddleware is my best bet, but I'm also not too upset with the current workaround so I may just stick with the "read only" way.

**Comment by TotallyInformation** [comment]
> But sioUse only provides the msg, so I didn't have a way to access the cookie from that middleware.

Yes, sorry about that. I'd forgotten. And the Socket.IO docs are abysmal.

> When the frontend receives the client connect msg, it sends an http request to `/ui/api/connect`. That route is handled by an `http-in` node in Node-RED.

Ahh, interesting. I keep hitting these issues about identification between the client and server. I will have a look at this again to see if it can help with the security features that I keep struggling with and can't find robust and relatively simple answers to.

Indeed, even today, I've added an experimental feature to vNext that, on first http connection sends a UUID to the client via a cookie. This is then replayed to the server on Socket.IO polling requests (typically the initial handshake) in the `x-clientid` header and to the `auth.clientId` property which is available in the server handlers, including sioMiddleware.js, as `socket.handshake.auth.clientId`.

Just pushed that change if you want to play with it. I've used `nanoid` to provide a cryptographically strong UUID for this. It will change every reload of the page though of course. I'll later extend so that the UUID can be set externally.

Also, I fixed the connect/disconnect control messages that were supposed to be issued on port #2 in your flows - I'd completely missed the fact that they were no longer happening. To make them more useful, I've added the client IP address and client ID to those messages to make them more useful.

Small steps but we are gradually getting somewhere useful hopefully!

**Comment by dczysz** [comment]
>I keep hitting these issues about identification between the client and server. I will have a look at this again to see if it can help with the security features that I keep struggling with and can't find robust and relatively simple answers to.

Yeah, it seems difficult to get a system that works well for everyone, since I'm guessing some people rely completely on uibuilder for security, and then others (like me) really don't need any of uibuilder's security features except one or two small pieces.

>Also, I fixed the connect/disconnect control messages that were supposed to be issued

I hadn't even noticed this, but I haven't hooked anything up to the vNext uibuidler node yet, just using it alone for quick UI testing.  Good to know it's no longer an issue though!

**Comment by TotallyInformation** [comment]
Fixed in v5/vNext
