### ISSUE TITLE
Warning MSG when Template Settings set to vue and/or  vue, bootstrap-vue

### ISSUE THREAD

**Issue by meeki007** [TotallyInformation/node-red-contrib-uibuilder#165]
Software / Version
Node.JS / v14.18.3
npm / 6.14.15
Node-RED / v2.1.5
uibuilder node / vNext 5.0.0-dev
uibuilderFE / 5.0.0-dev
OS / Ubuntu 18.04.6 LTS (Bionic Beaver)
Browser / Firefox 95.0

### How is Node-RED installed? Where is uibuilder installed?
Node-red installed @ $HOME/.node-red
uibuilder installed @ $HOME/.node-red/node_modules/node-red-contrib-uibuilder
uibuilder root folder @ $HOME/.node-red/uibuilder

Node: uibuilder node

Issue: Warning MSG when Template Settings set to vue and/or  vue, bootstrap-vue
```
WARNING

The selected uibuilder template (vue) is MISSING the following dependencies:
vue, bootstrap-vue

Please install them using the uibuilder Library Manager or select a different template.
```
I followed this install process

node-red dir
$ cd .node-red

Install vNext build
$ npm install TotallyInformation/node-red-contrib-uibuilder#vNext

NOTE: As of v3.1.3, npm cannot safely install the VueJS and bootstrap-vue default dependencies. If you want to use the provided VueJS templates, you must install these yourself. Either use uibuilder's library manager or manually install from the command line
While I was still in $HOME/.node-red
$ npm install vue@"2.*" bootstrap-vue@"2.*"
```
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1

> bootstrap-vue@2.21.2 postinstall /home/nfs/.node-red/node_modules/bootstrap-vue
> opencollective || exit 0

                                                                                                 
                                                              ;iiiiiiiiiiSSSSSSSSiiiiiiiiii;     
                                                              .rXXXXXXXXXrrrrrrrSXXXXXXXXXr.     
                                                              :iXXXXXXXX2. ;;;;, r3XXXXXXXi;     
                                                             ,rSSSSSXXXX2..sSSi: r3XXXSSSSSr,    
                                                              ,siiiiS2XX2. :;;:,.rXX2Siiiis,     
                                                               ,riiiii2X2..5XXXi .22iiiiir,      
                                                                .riiiii22..::::,,r2iiiiir.       
                                                                 .riiiii5SSiiiiS22iiiiir.        
                                                                   ;iiiii5X3333X5iiiii;          
                                                                    :iiiiiSXXXXSiiiii:           
                                                                     :siiiiSXXSiiiis:            
                                                                      ,siiiiiiiiiis,             
                                                                       .riiiiiiiir.              
                                                                        .riiiiiir.               
                                                                         .;iiii;.                
                                                                           ;ii;                  
                                                                            ::                   
                                                                             
                                                          Thanks for installing bootstrap-vue 🙏
                                                     Please consider donating to our open collective
                                                            to help us maintain this package.
                                                                             
                                                                Number of contributors: 0
                                                                  Number of backers: 304
                                                                  Annual budget: $14,458
                                                                 Current balance: $21,639
                                                                             
                                           👉  Donate: https://opencollective.com/bootstrap-vue/donate
                                                                             
npm WARN bootstrap@4.6.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.

+ vue@2.6.14
+ bootstrap-vue@2.21.2
added 18 packages from 24 contributors and audited 184 packages in 12.488s

18 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
looks like it installed fine
$ ls -a node_modules | grep vue
```
bootstrap-vue
portal-vue
vue
vue-functional-data-merge
```
Then restart node-red
$ sudo systemctl restart nodered

Tracked the WARNING MSG back to [uibuilder.html](https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/vNext/nodes/uibuilder.html) in line 5

Trying to figure it out now. Care to point me in the right direction for picking apart RED.settings.uibuilderTemplates[t].dependencies

**Comment by meeki007** [comment]
OK ive only dug for 35min and its not that bad. I wonder if your over thinking it.
I feel your issue with node-red's settings.js file. I'm one of the dreaded users that use different locations for it :) 
```
$ node-red -s /location/hidden/from/totallyInformation/for_fun_rename_it_too.js
```
So I agree unless the user is installing front-ends from within the node-red instance your not going to have a simple solution to this issue. Also users that are just upgrading the package may get caught in this issue.

Solution:
Is update the documentation and the install script MSG.

Previous MSG
```
======================================= [UIBUILDER PREINSTALL] =======================================
Please ignore warnings about missing peer dependencies for jquery, vue, bootstrap-vue
*** WARNING: npm is incapable of safely installing packages from within pre-/post-install scripts. ***
             So vue and bootstrap-vue are no longer installed by uibuilder.
             You must install them yourself using the command:
                 npm install vue@"2.*" bootstrap-vue@"2.*"
==================================================================================================
```
New MSG
```
======================================= [UIBUILDER PREINSTALL] =======================================
Please ignore warnings about missing peer dependencies for jquery, vue, bootstrap-vue
*** WARNING: npm is incapable of safely installing packages from within pre-/post-install scripts. **

	It's recommended that you install front-end packages within 
	the uibuilder's node Properties inside node-red's editor

	However if you know your uibuilder's uibRoot directory 
	normally located @ <userDir>/uibuilder
	You can install them yourself using the command:
	npm install --prefix /full-path-to/<userDir>/uibuilder vue@"2.*" bootstrap-vue@"2.*"
======================================= [UIBUILDER PREINSTALL] =======================================
```
The only issue is see with this is that I still need to make changes to the code so that the node_modules dir exists because you risk that npm might otherwise choose an already existing node_modules directory higher up in the hierarchy. [npm documentation on folders](https://docs.npmjs.com/cli/v8/configuring-npm/folders)

No need to do the work I'll get you a pull request on it.

**Comment by meeki007** [comment]
_to be brutally honest, that sounds like a VERY fragile process with a lot that can and probably will go wrong_

YES! also users like me will also change the node-red --userDir on command when spinning up individual instances on a static settings.js file.

**Comment by meeki007** [comment]
Closing Issue:

Fixed by [https://github.com/TotallyInformation/node-red-contrib-uibuilder/commit/b37789078e4d425fb11a0ba5040e356b06a2cbf9](https://github.com/TotallyInformation/node-red-contrib-uibuilder/commit/b37789078e4d425fb11a0ba5040e356b06a2cbf9)

Also another solution by [https://github.com/TotallyInformation/node-red-contrib-uibuilder/pull/166](https://github.com/TotallyInformation/node-red-contrib-uibuilder/pull/166)

**Comment by TotallyInformation** [comment]
> Because if I delete the last front-end package from this folder IT DELETE'S the /node_modules folder located inside the /home/nfs/.node-red/uibuilder dir. I would like it to be static and there even if no modules so if i submit a pull to update the documentation and the msg in the terminal upon build I could add the correct command.

That is by design of npm. The critical folder is the parent of that one. 

> I still need to make changes to the code so that the node_modules dir exists

Nope, npm will create the `node_modules` folder. You have to make sure that the parent of that exists and that is already done inside the node's initialisation.

> YES! also users like me will also change the node-red --userDir on command when spinning up individual instances on a static settings.js file.

Which is why any auto-install of dependent modules needs to happen aligned to the loading of the template that requires them.

Now that uibuilder has a robust framework for doing npm tasks, this is now feasible. Buried in the code somewhere is the code that loads a new template, it is triggered by an API call because you change the template from the Editor (and therefore your browser) but all the important work happens in the Node-RED runtime (backend server). There are 2 sets of API's currently and they sit in separate files, the older v2 API's and the newer v3. Over time, the v2 API's will get replaced.

So it wouldn't be that difficult to trigger an npm install for each required module (the modules are listed in the metadata in the template files). It would need to be optional though because there maybe reasons a user doesn't want modules installed for them (or at least not at the time they load the template).

**Comment by TotallyInformation** [comment]
Added to backlog.
