### ISSUE TITLE
Error in makeMeAnObject()  in uibuilderfe.js?

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#17]
in makeMeAnObject in uibuilderfe.js there is the line
`thing = { attribute : thing }`
I think this should actually be something like
`var save=thing`
`thing = {}`
`thing[attribute] = save`
There may well be a neater way of coding that. If the current code is wrong then the function might be better to test for object first.

**Comment by TotallyInformation** [comment]
Ah, yes, the problem is with the attribute part.

The ES2015+ way to do it is:

```
thing = { [attribute] : thing }
```

Annoyingly, IE doesn't support it.

So, the revised function will be:

```
function makeMeAnObject(thing, attribute='payload') {
    
    var out = {}

    if ( typeof thing === 'object' ) {
        out = thing
    } else {
        out[attribute] = thing
    }

    return out
} // --- End of make me an object --- //
```

**Comment by TotallyInformation** [comment]
Update pushed - version # for the module not changed but I've updated the version # for the fe code.

**Comment by colinl** [comment]
I don't think it actually mattered in the existing code, as far as I could see it is always called with an object anyway.

**Comment by TotallyInformation** [comment]
That's true but as it can also be used directly, it needs to be right :)
