### ISSUE TITLE
High-Res Logo : The logo on the github homepage is painfully low-res 

### ISSUE THREAD

**Issue by calumk** [TotallyInformation/node-red-contrib-uibuilder#174]
High-Res Logo : The logo on the github homepage is painfully low-res, and you can still see the red underneath.

Here is a Higher-res alternative

![NodeBlueHighRes](https://user-images.githubusercontent.com/1183991/160460412-008af7a3-ef2f-4804-ac9b-fd9adba49fff.png)

**Comment by xly01** [comment]
来信已收到，感谢！                                     此致                         敬礼！Tel：13372509117（谢礼阳）

**Comment by TotallyInformation** [comment]
Many thanks for this. In particular for tidying it up which I never got round to. :-) 

Of course, yours is nearly 50k vs 6k for the original. So I'll be uploading some smaller versions as well 1/2, 1/4, 1/8 size.

This is the 1/8 size (125x125):

![node-blue-125x125](https://user-images.githubusercontent.com/1591850/160471331-3e1bcbb6-476e-4ca3-9448-e83c5f32e3b7.png)
