### ISSUE TITLE
Non-standard JavaScript in socket.js@^5.0.0 causes Jest to fail

### ISSUE THREAD

**Issue by ewrayjohnson** [TotallyInformation/node-red-contrib-uibuilder#177]
Before logging an issue, please make sure that you are either on the latest npm version or the latest GitHub version.

Please ensure that as much of the following information is included as possible.

### Software and Package Versions

> Node.JS, Node-RED and uibuilder back-end versions are listed in the Node-RED log on startup. 
  `npm --version` shows the installed version of npm.
  From your browser's developer console (F12), the uibuilder front-end
  version can be seen by issuing the command `uibuilder.get('version').
  Please include all 5. Node.JS needs to be at least 4 but realistically, anything less than 6 is unlikely to work.

> Please also include your Operating System name and version and your browser's name and version. Any browser version less than n-2 or IE < v11 very unlikely to work without help from [polyfill.io](https://polyfill.io).

> I know it seems like a lot but it saves time in the long run

Software       | Version
-------------- | -------
Node.JS        | 12.22.1 
npm            | 6.14.12
Node-RED       | 2.2
uibuilder node | ^5.0.0
uibuilderFE    | 
OS             | Windows 10
Browser        | N/A

nodes/libs/scoket.js
Lines (42, 44, 46,and 48) with (Optional chaining) code below cause lint error: 'Expected an identifier and instead saw '.'
`?.
`  
Prior version 4.1.4, does not have the offending code.

**Comment by ewrayjohnson** [comment]
Updated Jest

**Comment by TotallyInformation** [comment]
Just noticed that optional chaining `?.` came in with Node.js v14 - so I probably shouldn't have included it or I should have updated the minimum node version to 14. 

A bit late now but I'll be updating the minimum node version when v12 drops out of support. Which actually is only the end of this month!
