### ISSUE TITLE
Change to use get-installed-path 4.0.3 breaks paths

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#18]
Commit e70e116: 
Bump version to 4.0.3, change getInstalledPath.sync to getInstalledPathSync for change to gip v4
breaks the paths so that the paths to normalize, jQuery etc are not found. I have manually reverted get-installed-path back to "^3.0.1" in package.json and the associated calls back to getInstalledPath.sync and all is well again. Haven't investigated further as trying to look at the webpack issues at the moment.

**Comment by colinl** [comment]
The call to getInstalledPathSync is generating an exception:
ReferenceError: getInstalledPathSync is not defined
If I replace 
const ... getInstalledPath = require('get-installed-path')
with
const { getInstalledPathSync } = require('get-installed-path')
then it works.

**Comment by TotallyInformation** [comment]
Thanks Colin, spotted that locally and forgot that I'd also pushed it. Fixed in my next push.

**Comment by TotallyInformation** [comment]
Update pushed.
