### ISSUE TITLE
Setting loadStylesheet to false in uibuilder.start() options is not working (v5.1.1)

### ISSUE THREAD

**Issue by unborn-andy** [TotallyInformation/node-red-contrib-uibuilder#184]
When using the new `uibuilder.esm.js` module, i noticed that because i wasnt loading a css file (all css was in each .vue file)
the `uib-brand.css` file was loading but clashing with existing bootstrap-vue css styles.

So i tried to pass the `loadStylesheet` option setting it to `false` .. but that didnt make a difference.

`uibuilder.start({ ioNamespace: "/navbar", loadStylesheet: false });`

As a workaround i loaded a fake css so the code responsible of loading uib-brand.css wouldnt kick in ?

Software       | Version
-------------- | -------
Node.JS        | v16.15.1
npm            | 
Node-RED       | v3.0.0
uibuilder node | v5.1.1
uibuilderFE    | uibuilder.esm.js
OS             | Windows 11
Browser        | Firefox 102

**Comment by TotallyInformation** [comment]
Thanks Andy. Will investigate. Not been coding due to an injury recently, just getting back in now.

**Comment by TotallyInformation** [comment]
Committed to v6 branch.
