### ISSUE TITLE
ReferenceError: io is not defined while using uibuilder.start() from uibuilderfe library

### ISSUE THREAD

**Issue by ndassgit** [TotallyInformation/node-red-contrib-uibuilder#192]
I am working on a quasar/vue.js web front end application communicating to a remote node red server. While using uibuilderfe frontend library's uibuilder.start() to pass a different ioNameSpace, I get the reference error with socket.io-client (io) object. I believe the error is because of the blocked scope in the following lines.

```js
if (typeof require !== 'undefined'  &&  typeof io === 'undefined') {
    const io = require('socket.io-client')
} 
```

Changing "const" to "var" or "let" outside the block seem to resolve the reference error.

Node.JS	-->16.17.0
npm	 -->8.15.0
Node-RED Remote	-->3.0.0
uibuilder  version -->5.1.1
uibuilderFE --> Uibuilderfe.js
OS	--> Windows 10
Browser -->Edge 107, Firefox 102

Thank you.
Navs

**Comment by TotallyInformation** [comment]
Could you please share the actual error and the code you've used?

It's been a while since I've exercised that part of the code so I need to remind myself of how to do it.

Also, have you tried the new client?

**Comment by ndassgit** [comment]
Thanks for your quick response, Julian.

Here is the code where uibuilder.start is called.
=================================================================================
import { boot } from "quasar/wrappers";
import { LocalStorage } from "quasar";
import { uibuilder } from "node-red-contrib-uibuilder/front-end/uibuilderfe";

export default boot(({app}) => {

	
	app.config.globalProperties.$uibuilder = uibuilder;
	console.log(uibuilder);
	// add uibuilder to global Variable.
	// if (typeof globalThis.uibuilder === 'undefined') {
	// 	Object.defineProperty(globalThis, 'uibuilder', {
	// 	  value: {
	// 		uibuilder
	// 	  },
	// 	  enumerable: false,
	// 	  configurable: true,
	// 	  writable: true,
	// 	});
    //	}
    
	let uib_namespace = "https://" + LocalStorage.getItem("masmw_server") + "/" + process.env.UIBUILDER_NAMESPACE;
	console.log(uib_namespace);
	let uib_iopath = process.env.UIBUILDER_SOCKET_IO_PATH;
	uibuilder.start(uib_namespace, uib_iopath, app);  // line 28 fails with a Reference Error
	 
		
});
=================================================================================
![image](https://user-images.githubusercontent.com/11790334/205134026-6a1151ca-904f-48c6-ac90-eecbd0c96898.png)

**Comment by TotallyInformation** [comment]
First thing to note is that Vue hasn't loaded. So something is off with your HTML which you haven't shared.

Then it looks like you have used ESM `import` statements - unless you are loading all of your scripts as modules in the HTML and using only suitable modern browsers, that won't work.

Also, if you loaded quasar as a module (which is what the import statements are doing) but you loaded uibuilderfe as a standard script, your browser will not allow the 2 to talk to each other. 

If you want to use ESM, you really need to be using the new library `uibuilder.esm.js` loaded as a module but you need to refer to the documentation to see how to make everything work together - this isn't a uibuilder problem, it is the crazy way that ESM has been architected in JavaScript.

**Comment by ndassgit** [comment]
Thanks again for you quick response. I created a boiler-plate test-vue project (npm init vue@latest) and imported uibuilderfe using the script tag in the html below. However, I still get the reference error.
********************************************************************************************************************** 
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vite App</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
    <script src="uibuilder/uibuilderfe.min.js"></script>
    <script>

      // run this function when the document is loaded
      window.onload = function() {
        if (uibuilder) {

          alert("uibuilder is intiated!");
          //uibuilder.start("https://remote.nodered.server.com/uib-test");

        }
      // Start up uibuilder - see the docs for the optional parameters
         // uibuilder.start()

          // Listen for incoming messages from Node-RED
          uibuilder.onChange('msg', function (msg) {
            console.info('[indexjs:uibuilder.onChange] msg received from Node-RED server:', msg)

            // dump the msg as text to the "msg" html element
            const eMsg = document.getElementById('msg')
            eMsg.innerHTML = window.syntaxHighlight(msg)
          })
      }
       
    </script>
  </body>
</html>

********************************************************************************************************************
![image](https://user-images.githubusercontent.com/11790334/206291904-58c5ed82-391b-428a-9f82-5ba59fee467e.png)
********************************************************************************************************************
I then tried with the previous version of uibuilderfe, it worked. The difference I see in the previous version is, it is "var io = require("socket.io-client") oppose to const.
********************************************************************************************************************
![image](https://user-images.githubusercontent.com/11790334/206292759-4d071a92-ccd9-4f10-b496-69f57ac2e4aa.png)

**Comment by TotallyInformation** [comment]
`<script src="uibuilder/uibuilderfe.min.js"></script>` - is incorrect. It should be `<script src="../uibuilder/uibuilderfe.min.js"></script>` (note the leading dots).

`<script type="module" src="/src/main.js"></script>` - as mentioned previously, this is the issue. There is no scope overlap between an ESM and a traditionally loaded script.

You can switch to the new client by removing the reference to uibuilderfe and replacing it with an import statement in your main.js file:

```
import '../uibuilder/uibuilder.esm.min.js'
```

You will also need to fold what is in the other script at the end of your html file into your main.js file because that too has no access to what is happening within an ESM script.

Please refer to the documentation at https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uibuilder.module?id=esm-version and [here](https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uibuilder.module?id=more-information-on-the-esm-version).

You will also need to adjust your `uibuilder.start` since the [new library only accepts a single parameter containing an object](https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uibuilder.module?id=start-function-now-rarely-needed):

```
uibuilder.start( {
    ioNamespace: "https://remote.nodered.server.com/uib-test"
} )
```

Also check out  https://totallyinformation.github.io/node-red-contrib-uibuilder/#/uibuilder.module?id=troubleshooting.

**Comment by ndassgit** [comment]
Many Many Thanks Julian. I'll try this approach.

**Comment by TotallyInformation** [comment]
No updates so assuming all is well now? Closing issue. Please reopen if the issue remains.
