### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'cssRules')

### ISSUE THREAD

**Issue by Wavebreakers** [TotallyInformation/node-red-contrib-uibuilder#201]
https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/5b267747282b6589f59f33df272cacfac341a60b/src/front-end-module/uibuilder.module.js#L2574

Expression: `document.styleSheets.length === 0 && ...` will lead to `Uncaught TypeError: Cannot read properties of undefined (reading 'cssRules')`.

**Comment by TotallyInformation** [comment]
Hey, how did that creep through! I think that should be 
`if ( document.styleSheets.length >= 1 || (document.styleSheets.length === 1 && document.styleSheets[0].cssRules.length === 0) ) { `

Did that actually trigger an error for you or did you just spot the issue reading the code?

Will be fixed for the next release but if it is causing you an immediate issue, I can get out a quick bug-fix.

**Comment by TotallyInformation** [comment]
I'll try to get something out shortly.

**Comment by TotallyInformation** [comment]
Fixed in v6.2.0 which is about to be published.
