### ISSUE TITLE
Vite dev server fails to establish WebSocket connection

### ISSUE THREAD

**Issue by StonkGodCapital** [TotallyInformation/node-red-contrib-uibuilder#202]
Software       | Version
-------------- | -------
Node.JS        |  18.15
npm            |  9.5.0
Node-RED       |  latest
uibuilder node |  latest
OS             |  OSX / Ubuntu
Browser  | Safari / Chrome
Vue | 3
Vite | 4.1.4

Probably back burner but I've tried just about everything I can think of to get this working and I'm just not quite sure what it could be so hoping you have an idea 😀

I have Vite up and running and the app builds just fine. When accessing the built app normally, everything functions flawlessly and the dev server works as well, however, the dev server is unable to establish a connection with uibuilder (page loads, just no information is exchanged). I'm using the proxy settings from the Wiki entry and the esm module.

There are two errors that are sent back in the connection attempts:

```
[Uib:ioSetup:connect_error] ❌ Socket.IO Connect Error. Reason: Invalid namespace Error: Invalid namespace
    at Socket2.onpacket (uibuilder.esm.js:2330:21)
    at Emitter.emit (uibuilder.esm.js:239:21)
    at uibuilder.esm.js:2912:12
```

and

```
{
    "code": 1,
    "message": "Session ID unknown"
}
```

Any help would be appreciated!

**Comment by TotallyInformation** [comment]
Can you share which WIKI entry you are using - it is possibly out of date.

If you are using the latest versions of uibuilder, most build servers require you to specify the Socket.IO `ioNamespace` as in the docs here: 

https://totallyinformation.github.io/node-red-contrib-uibuilder/#/front-end-builds?id=using-a-build-development-server

**Comment by StonkGodCapital** [comment]
Alas that was the one thing I hadn't tried, had messed with the namespace property on the start function but not that ioNamespace. Added that and disabled the proxy all together and it's working as expected, thank you so much!

**Comment by StonkGodCapital** [comment]
> Can you share which WIKI entry you are using - it is possibly out of date.
> 
> If you are using the latest versions of uibuilder, most build servers require you to specify the Socket.IO `ioNamespace` as in the docs here:
> 
> https://totallyinformation.github.io/node-red-contrib-uibuilder/#/front-end-builds?id=using-a-build-development-server

Also to answer the above, I used the wiki page located here: https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Basic-Vite-Vue-3-TypeScript-App

It's mostly still current, the uibuilder.start needs modified and the proxy configuration is optional.

**Comment by TotallyInformation** [comment]
Thanks for sharing the link. I've added a note to that article reminding people to provide the namespace when using a live dev-server.
