### ISSUE TITLE
Default Blank Template is Not the same as video 

### ISSUE THREAD

**Issue by PLCMercenary** [TotallyInformation/node-red-contrib-uibuilder#203]
Software       | Version
-------------- | -------
Node.JS        | 18.7.0
npm            | 8.15.0
Node-RED       | 3.0.2
uibuilder node | 6.1.1
uibuilderFE    | 6.1.1-iife.min
OS             | fedora server 36 (where NR is running) accessed from MacOS ventura
Browser        | Brave [Version 1.48.171 Chromium: 110.0.5481.177 (Official Build) (arm64)]

### How is Node-RED installed? Where is uibuilder installed?
NodeRed is running on docker container pulled from dockerhub using Latest tag. Container is on fedora 36 server. UI builder was installed via palette manager a while ago; never used, updated via palette manager to 6.1.1 to follow the uibuilder #001 video that was recently posted to youtube. 

UI builder 6.1.1 FE template that loads with the default Blank Template, No Framework settings is different from the template that is loaded in the video. The blank template that loads by default when following step by step with the video, does not include either of the send event button or send msg back to nodered button. Nor does it contain the message viewing area. 

the template that loads by default has a heading of uibuilder Blank Template and some smaller text that says "using the IIFE Library" and does not look at all like the default template shown in the uibuilder 001 video. 

steps to reproduce: 
1. Browse to NR visual editor
2. open palette manager from hamburger menu (right side)
3. select install tab and search for uibuilder
4. install node-red-contrib-uibuilder 6.1.1 and wait for installation to complete
5. from ssh terminal session with fedora server run "docker-compose restart [NR container service name]"
6. observe container restarts 
7. refresh browser at NR editor. 
8. New Flow tab
9. Following video, drop uibuilder node onto workspace. 
10. add inject node and debug nodes IAW video
11. open uib configuration panel
12. enter a URL "testuib"
13. click done then deploy. observe UIB triangle is gone, node appears happy
14. open uib config panel and select button to OPEN
15. observe new browser tab shows template with uibuilder Blank Template header text and smaller text that reads "Using the IIFE Library" 
16. cannot follow video any further.

**Comment by PLCMercenary** [comment]
After finding the recent change to make the blank template to be blank and after reading the change logs about the example additions, I got the bright Idea to watch the most recent video on UI builder and I am glad that I did... Excellent work to everyone contributing to this effort, and mega thanks to TI for the video walk throughs and through example contents. Closing this issue.

**Comment by TotallyInformation** [comment]
Many thanks for the comments.
