### ISSUE TITLE
index.css and index.js files are re-created after deleting/moving

### ISSUE THREAD

**Issue by vvaldersteins** [TotallyInformation/node-red-contrib-uibuilder#21]
Index.css and index.js files are being re-created after they are moved or deleted outside of the src folder. 

Is it possible to disable this?

**Comment by TotallyInformation** [comment]
Adding a new option to the admin ui to disable copying of index.css and index.js

Won't disable index.html though as without this, the app won't work.

**Comment by TotallyInformation** [comment]
Please try branch 0.4.8 which this enhancement.
