### ISSUE TITLE
Unresponsive after a small amount of time.

### ISSUE THREAD

**Issue by james-barrett** [TotallyInformation/node-red-contrib-uibuilder#233]
### Current Behavior

opening the website is fine and responsive, after a short amount of time it stops responding to events

### Expected Behavior

a normal working website

### Steps To Reproduce

i would need to share my code, I've done nothing unusual.

### Example Node-RED flow

```
paste your flow here
```

### Environment

- UIBUILDER version: latest
- Node-RED version: latest
- Node.js version: latest
- npm version:  latest
- Platform/OS: rasp pi 4 - browser and testing done from arch linux
- Browser:  chromium

How is Node-RED installed? (globally/locally? admin/user?): globally on pi using the node red bash script

How/where is UIBUILDER installed (palette-manager/globally/locally? Which folder?) rasberry pi 4 - node red - standard via palette manager

Have you changed any of the `uibuilder` settings in your `settings.js` file? No

EDIT

HTOP shows no signs of high load on the pie, my test laptop is also low load, it might be something im doing wrong with the constant flow of data to the web interface

**Comment by TotallyInformation** [comment]
Hi James, I'm afraid without code to try and reproduce the issue, there is not much I can do to help. It is certainly working for other people and all my tests are working.

**Comment by james-barrett** [comment]
Great thanks for your reply, i'm going to try and restructure my code and i will follow on here with examples for mark it complete if i correct the issue in doing so. Thank you

**Comment by james-barrett** [comment]
It seems that the issue was mine, bad coding i guess but since I've restructured my code all is working very well, thanks for the great software.

**Comment by TotallyInformation** [comment]
Thanks James.
