### ISSUE TITLE
Disable "Save" Button for Users with Read Permissions

### ISSUE THREAD

**Issue by d-mansfield** [TotallyInformation/node-red-contrib-uibuilder#234]
### Request

I went into the NodeRed settings.js file and set up 2 users - one with admin (*) permissions, one with read permissions.

The user with read permissions cannot deploy changes in NodeRed, but was able to edit files inside of UIBuilder and save the changes.

Is there any way to disable the "Save" button on the "FIles" tab of UIBuilder if the user is read only?

**Comment by TotallyInformation** [comment]
Hi Dustin, I've never had much luck with Node-RED's admin permissions. I did try in the past to make use of it but it only ever caused issues. So at this point, there is no relation between the admin permissions and the uibuilder files.

And in any case, while I could limit the in-node editor, you would still be able to edit the files directly of course.

So the best approach is to use the filing system access control system and sync the node-red admin settings with user logins or something like that.

Happy to consider additional changes but as I say, I've never managed to get anything sensible out of Node-RED's admin permissions.

**Comment by srujanmelam** [comment]
is the issue fixed ?

**Comment by TotallyInformation** [comment]
No, please read my last comment. It is not fixable by me. I'd be happy to consider a PR if you have a solution but my previous solutions did not work and caused other issues.

**Comment by srujanmelam** [comment]
i would love to contribute... please bare with me if i got any issues with local set up.. that would be really helpful
