### ISSUE TITLE
settings file requires updating

### ISSUE THREAD

**Issue by vanderstack** [TotallyInformation/node-red-contrib-uibuilder#28]
Hello. The file below has a bug on line 209:
node-red-contrib-uibuilder\nodes\uibuilder.js

it assumes that there is a settings block in the node red settings.json file for uibuilder. i am brand new to node red and had no idea this was even an option. it was very painful to hunt down, but as soon as i added a uibuilder block to my node red settings file everything worked. following the source, i discovered you are checking the settings.uibuilder.middleware property directly without first checking that settings.uibuilder is not undefined.

 /** Provide the ability to have a ExpressJS middleware hook.
         * This can be used for custom authentication/authorisation or anything else.
         * The function must be defined in settings.js
         * @since v1.0.3 2017-12-15
         */
        var httpMiddleware = function(req,res,next) { next() }
        **if (RED.settings.uibuilder.middleware) {**
            /** Is a uibuilder specific function available? */
            if ( typeof RED.settings.uibuilder.middleware === 'function' ) {
                httpMiddleware = RED.settings.uibuilder.middleware
            }
        } else if (RED.settings.httpNodeMiddleware) {
            /** If not, see if the Node-RED one is available and use that instead.
             * Use httNodeMiddleware function which is defined in settings.js
             * as for the http in/out nodes - normally used for authentication
             */
            if ( typeof RED.settings.httpNodeMiddleware === 'function' ) {
                httpMiddleware = RED.settings.httpNodeMiddleware
            }
        }

**Comment by TotallyInformation** [comment]
Well spotted but I think that is already fixed in the latest version? Sorry, not at my computer at present and hard to check on my mobile.

**Comment by vanderstack** [comment]
no problem, i'm beyond the issue and was just hoping to help in case anyone else was stuck. speaking of being on mobile, what app did you use to get a notification via github so quickly for the new issue?

**Comment by TotallyInformation** [comment]
It’s fine. I would always rather people report stuff than not. :)

**Comment by TotallyInformation** [comment]
Re comments. I actually have GitHub linked both to Slack and to Telegram. I get notifications on both! I should disconnect one but never get round to it.

**Comment by TotallyInformation** [comment]
I was using Telegram before I started to use Slack. I use Telegram as a bit interface to Node-RED.
