### ISSUE TITLE
Refusing new connections 

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#3]
On a system which has been running untouched for several days it suddenly seemed to stop accepting new connections. For example a uibuilder view in firefox continues to work ok and I can even shut down the browser for an extended period and re-open the view and it continues ok. However if I open it in Chrome on that PC or on an android device the initial page shows ok but the websocket never connects (I have a connection status on the page). The only message I can see in the log which might be relevant is
18 Sep 20:33:17 - [warn] Communication send error: Error: not opened
which might correspond to the time at which the issue started. There is only one such message in the log. There is nothing in the debug log in the flow editor. Making a trivial change and re-deploying does not fix the problem.
Restarting node-red does fix the problem. I have seen this happen twice but did not analyse it sufficiently the first time to know whether the error message appeared last time.

Node-RED version: v0.17.5
Node.js  version: v6.11.3
Linux 4.9.35-v7+ arm LE
UI Builder - Version 0.3.1 started at /uibuilder

**Comment by TotallyInformation** [comment]
If you could check your browser console (F12) as well when you see this, can you check there for errors as well?

If it works in FF but not Chrome, that would seem to indicate a problem with Chrome. I am using Socket.IO for websocket comms rather than raw websockets as it handles a lot of the details and can fall back to non-socket comms if something blocks websockets (common on corporate networks for example) but it does come with it's own baggage.

**Comment by colinl** [comment]
Yes, I realised after I restarted node red that I should have checked the console. I had forgotten that on Android the browser is Chrome, but you are right that could be a factor. I have the normal dashboard running on the same pi and it does not show the issue so it could be that chrome with uibuilder is the issue. I will have to wait for it to fail again before I can do that.

**Comment by colinl** [comment]
Aha! It is not a chrome related issue, once it fails, it fails on Chrome on a PC and on Android, but also on Firefox on a second PC.  Looking at the log on the failing machine all I see is
Document Ready: IO Namespace: /undefined
Which I suspect is a problem. The reason is that in index.js I have 
ioNamespace = '/' + readCookie('uibuilder-namespace')
and readCookie (from your original sample code) is failing because document.cookie is empty.
Having restarted node-red then document.cookie is set to "uibuilder-namespace=home"

**Comment by TotallyInformation** [comment]
Hmm, interesting. I wonder why the namespace is not being found. Do you have any extensions that block cookies? 

I think I may have to do it a different way. The only purpose for the cookie is to set the namespace for Socket.IO which, in turn, allows you to have multiple uibuilder instances active without them all getting all of the messages from NR.

In hindsight, I can probably get the namespace from the URL instead. I will try that and issue another update. At work at the moment so it will be this evening if I can get time.

**Comment by colinl** [comment]
No I am not running a cookie blocker, and if I re-start node-red and then reload the page it works correctly.

**Comment by TotallyInformation** [comment]
Could you try adding the following to the front-end `index.js`?

```
// Get the namespace from the current URL rather than a cookie which seems unreliable
debug && console.log(ioNamespace)
var u = window.location.pathname.split('/')
ioNamespace = u.pop()
if (ioNamespace === '') ioNamespace = u.pop()
ioNamespace = '/' + ioNamespace
// if last element is '', take [-1]
debug && console.log(ioNamespace)
```

It should take the namespace from the url instead of the cookie but will still output debug messages of both versions.

**Comment by colinl** [comment]
OK, running ok so far. Will have to run for a while to see if it has fixed it.

**Comment by colinl** [comment]
The situation where the cookie had expired (or whatever has gone wrong with it) has occurred and the url method successfully provided the namespace. Is there any point leaving the cookie stuff in?

**Comment by TotallyInformation** [comment]
Super, thanks for confirming that. No, the cookie part isn't needed, I'll take it out at some point.
