### ISSUE TITLE
It sends out more than 1 command after a while

### ISSUE THREAD

**Issue by haydendonald** [TotallyInformation/node-red-contrib-uibuilder#33]
It might be something to do with having a client connect, loose connection, and reconnect.
The node basically will start to send out more than 1 command on its output

So
when i send say "hi" though the website using the send method
the output will send out
"hi"
"hi"
"hi"
all at once. (not the same msg object)

It also seems to loose commands that were sent in this state causing buttons to be laggy.

**Comment by colinl** [comment]
Are you sure it is not hitting your send code multiple times?  You could include a timestamp in the "hi" message to check.

**Comment by haydendonald** [comment]
I'm pretty sure it's not, I tested it with console.logs, but i can check tomorrow for the timestamps :)

**Comment by TotallyInformation** [comment]
Are you using the latest version? There used to be a problem like that. I can happen if the node instance can't remove the previous socket when redeploying. I've updated the node several times to try and improve that but there are some limitations with Socket.IO.

**Comment by haydendonald** [comment]
Yeah i am, it could be related to that. The issue is very obvious during my development redeploying over and over.

**Comment by colinl** [comment]
Did you check with timestamps in the message to make sure it is the same message multiple times and not that it is getting to your send multiple times?

**Comment by haydendonald** [comment]
Hi, ok so i'm using the default webpage.
Here's some pics that might explain the issue.

NR: https://ibb.co/jy16mn
Web: https://ibb.co/h1RiXS

Console output with debug front end on:
index.js:110 msgCopy changed. New value:  Object
uibuilderfe.min.js:1 uibuilderfe: msg sent - Namespace: /TESSTT, Channel: uiBuilderControl
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client"}
uibuilderfe.min.js:1 2
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  2
uibuilderfe.min.js:1 uibuilderfe: SOCKET CONNECTED - Namespace: /TESSTT
uibuilderfe.min.js:1 true
index.js:128 Socket.IO Connection Status Changed:  true
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 3
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  3
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 4
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  4
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 5
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  5
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 6
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  6
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 7
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  7
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 8
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  8
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"client connect","cacheControl":"REPLAY","debug":true,"_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP","from":"server"}
uibuilderfe.min.js:1 9
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  9
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 10
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  10
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 11
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  11
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 12
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  12
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 13
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  13
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 14
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  14
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 15
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  15
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"uibuilderCtrl":"ready for content","cacheControl":"REPLAY","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 16
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  16
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 17
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  17
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 18
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  18
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 19
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  19
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 20
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  20
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 21
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  21
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 22
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  22
uibuilderfe.min.js:1 uibuilder:socket.on.control - msg received - Namespace: /TESSTT
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"cacheControl":"REPLAY","uibuilderCtrl":"manual send","from":"client","_socketId":"/TESSTT#Hx-UX4X0qZExGK2UAAAP"}
uibuilderfe.min.js:1 23
index.js:141 New control msg sent to us from Node-RED over Socket.IO. Total Count:  23
index.js:148 Sending a message back to Node-RED - after 2s delay
uibuilderfe.min.js:1 uibuilderfe: msg sent - Namespace: /TESSTT, Channel: uiBuilderClient
uibuilderfe.min.js:1 Object
uibuilderfe.min.js:1 {"topic":"uibuilderfe","payload":"I am a message sent from the uibuilder front end"}
uibuilderfe.min.js:1 1
index.js:134 New msg sent to Node-RED over Socket.IO. Total Count:  1

**Comment by IanRyb** [comment]
Same here, im getting 179 messages at once on every page load :(

**Comment by TotallyInformation** [comment]
OK, thanks. As you know, the workaround is to occasionally restart NR. You might also check to see if a full deploy is better - probably not but worth a try.

I still don't know what is causing this so I'm not sure how to fix it. All suggestions welcome!

**Comment by haydendonald** [comment]
Not sure but it could be related to node red not actually clearing variables and stuff on redeploy. Do you handle the close? event correctly? I remember i had a problem where i had multiple messages sending out with my HDL interface and that was because i didn't close and clear the udp socket correctly. You might be having the sameish problem

**Comment by TotallyInformation** [comment]
I do handle the close event as best I can. However, I've had problems with both Express routes and Socket.Io as you will probably see from the comments in the source code.

Clearly something is not being cleared out properly. Maybe a new set of eyes might spot the problem. You can turn on full debugging in uibuilder itself from your settings.js file. You get a log file. I'd be grateful if you managed to find time to walk through that and see if you can spot anything.

**Comment by DeviousPenguin** [comment]
Hi, I'm getting the exact same issue, if I refesh the browser with the page that UIBuilder is serving up it causes the multiple messges from UIBuilder -> Node-RED. It can also happen if the flow is running for longer than a few minutes, so I'm not really sure what's causing it.

I'm not hitting the multiple times as I'm using moon.js and pure.css to disable the button after a single press using 'pure-button-disabled' CSS class.

I'm also seeing

> (node:32646) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit

In my Node-RED console output also; Once I restart Node-RED I go back to a single message from UIBuilder -> Node-RED.

System Info:
Node-RED version: v0.18.4
Node.js  version: v8.11.1
Linux 4.4.0-83-generic x64 LE (Ubuntu 16)

A fix for this would be great, right now I'm restarting Node-red once an hour because of this issue.

**Comment by kazsharp** [comment]
Hi, I have the same issue.
When I deploy flows and reload blowser, a new websocket is connected.

I assume that connections don't close properly when I deploy.
I checked the code of 'uiblib.js' and I found that 'ioNs.connected[socketId].disconnect()', line 78, didn't execute.
I tried commenting out 2 lines,
'setNodeStatus({fill: 'red', shape: 'ring', text: 'CLOSED'}, node)' line 69,
'sendControl({ 'uibuilderCtrl': 'shutdown', 'from': 'server' }, ioNs, node)' line 72,
then this issue doesn't happen.
I understand it is the right way but I hope this will help.

**Comment by kazsharp** [comment]
Hi, 

I resolved.
To call the functions 'setNodeStatus' and 'sendControl', 'this.' are needed.

Edit code as follows
this.setNodeStatus({fill: 'red', shape: 'ring', text: 'CLOSED'}, node) line 69,
this.sendControl({ 'uibuilderCtrl': 'shutdown', 'from': 'server' }, ioNs, node) line 72

Regards

**Comment by TotallyInformation** [comment]
@kazsharp, many thanks for this post.

Others in this thread, could you please try the above fix and see if that does it for you?

For more exact information, the 2 locations are:

https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/master/nodes/uiblib.js#L69

and

https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/master/nodes/uiblib.js#L72

Please report back so that I can then incorporate this change if needed.

Many thanks.

**Comment by DeviousPenguin** [comment]
Hi, thanks for this, I've updated my uiblib.js file, I found it in:

    ~/.node-red/node_modules/node-red-contrib-uibuilder/nodes/uiblib.js

on my Ubuntu system.

I've restarted NodeRED and so far things seem to be working great, no more repeated messages even when refreshing the page from uibuilder.

It's only been running a few minutes, but so far so good; I'll edit this post if I see repeated messages again.

**Comment by DeviousPenguin** [comment]
Just a quick update, my flow has been running for 12 hours now and still no repeated messages for me.

Also my console output from NodeRED is no longer showing the 

    (node:32646) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 disconnect listeners added. Use emitter.setMaxListeners() to increase limit

error so this issue seems to be resolved, for me at least. Thanks!

**Comment by TotallyInformation** [comment]
Many thanks to Ellie for submitting a PR. Expect to see a new v1.0.8 published to npm soon.
