### ISSUE TITLE
Is "Example: RiotJS" suitable?

### ISSUE THREAD

**Issue by kazsharp** [TotallyInformation/node-red-contrib-uibuilder#34]
Hello.

I  like the uibuilder, especially when I use it with Riot.js.
Using uibuilder, I can use websocket spontaneously, but "Example: RiotJS" uses websocket expressly.

Don't you think it is more appropriate  example uses internal websocket (by including uibuilderfe.min.js in index.html)?

Thank you.

**Comment by colinl** [comment]
If you look at the extended riot example you will see it does include uibuilderfe.min.js

**Comment by kazsharp** [comment]
Thank you  for replying.

I know the extended riot example include uibuilderfe.min.js, and I think it is good example.
On the other hand, I don't think the basic riot example is very good.
It doesn't show the merit of uibuilder.

I can show you the sample, if necessary.

**Comment by colinl** [comment]
The original riot example is Julian's, so he would have to comment on this, it dates back to the very beginnings of uibuilder.  You could add your example to the wiki and Julian could then decide whether the original is still relevant.
Even the extended one is very old, do you know whether it still works as it is?

**Comment by TotallyInformation** [comment]
Hi Kaz, thanks for raising and spotting this. And thanks for using uibuilder.

As Colin says, the old basic Riot example is rather outdated and I'd forgotten about it. Perhaps it would be best to remove it unless you have a better example.

By the way, I'm always happy to have more examples in the WIKI so please feel free to add something if you think others might benefit.

**Comment by kazsharp** [comment]
I modified the example.
I tried to keep the original code as much as I can.

Please tell me if there is a problem.
(because I 'm not used to GitHub)

And I'll add other examples.

Thank you all!

**Comment by TotallyInformation** [comment]
Thanks Kaz, I will check it out. I will close this issue for now if that is OK.

Many thanks for contributing. Also, don't forget that we have a Slack channel available too.
