### ISSUE TITLE
Request : add external server address

### ISSUE THREAD

**Issue by IanRyb** [TotallyInformation/node-red-contrib-uibuilder#35]
Hi,
Im trying to deploy front-end on ASP .NET on separate web-server but uibuilderfe does not contain any possibility to connect to external uibuilder socket as its looks to actual url.

For example uibuilder deployed at : 10.10.10.10:1880/uibuilder
Web server are on : 20.20.20.20

So i've changed definition of ioNamespace to
`self.ioNamespace  = "/ui"  `
added
serverAddr variable
and changed socket initialization to 
`self.socket = io(self.serverAddr + self.ioNamespace, { path: self.ioPath, transports: self.ioTransport })`

Seems like everything works, but im not pro in js or nodejs, so i guess i've done it all wrong and i hope You can add this feature in right way.

Thanks 😄

**Comment by TotallyInformation** [comment]
Hi Ian, thanks for raising this.

The primary purpose of uibuilder is to deliver a ui from the same server as Node-RED just as the core Dashboard does.

However, if there is some easy way to change the uibuilderfe.js library to make it possible to use from another server, I'd be happy to enable that to happen.

Please submit a pull request if you know how to do that. That way, I can see and review the whole change. It does sound like it should be an easy change to make.

Let me know if you don't know how to do a pull request, I'd be happy to talk you through it.

**Comment by TotallyInformation** [comment]
Hi Ian,

Apologies this has taken so long.

Please note that, when v2 is released, it has the capability to consume the socket.io connection from a server different to the on serving up the pages.

To achieve this, the communications no longer start automatically but instead by using the `uibuilder.start()` function in your own `index.js` or equivalent.

To use uibuilder with pages from a different server, simply pass the socket.io namespace and ioPath defined by the uibuilder node instance. `uibuilder.start(namespace,ioPath)`,

You can find the namespace and ioPath using the "details" webpage that you will find a link to in the admin ui. Open the admin panel for an instance of uibuilder, click on "Path & Module Details" then on the "Details" link.
