### ISSUE TITLE
Request: React basic tutorial

### ISSUE THREAD

**Issue by teddybee** [TotallyInformation/node-red-contrib-uibuilder#36]
I am trying to integrate React with your uibuider. In the userVendorPackages I set the react package, put the uibuilder node in the flow, but it is searching the /myapp/src/index.html which is not there. I am using the create-react app script for generating the basic app template. Can't figure out how the /myapp/build dir will be served...
It would be great if you could explain this in a short wiki page or make some preferences in the settings or uibuilder node to have a possibility to host the build dir.

**Comment by teddybee** [comment]
Sorry, I thought ReactJs and React are two different animals (different names, packages).
I understood the key tasks from your tutorial, please delete this issue.

**Comment by TotallyInformation** [comment]
Thanks @teddybee
