### ISSUE TITLE
(Minor documentation issue) Incorrect descriptions on Issue Template?

### ISSUE THREAD

**Issue by alastaira** [TotallyInformation/node-red-contrib-uibuilder#370]
### Current Behavior

I might be wrong, but when filing an issue against the UIbuilder repo, the choices/descriptions look incorrect?
![image](https://github.com/TotallyInformation/node-red-contrib-uibuilder/assets/901056/193d4d57-db1e-4d3d-99ff-40a4be8f613a)

### Expected Behavior

I would have expected the top link/description to be for filing an _issue/bug_ relating to uibuilder, and for the second link/description to be for filing a _feature request_ relating to uibuilder (and this is indeed what the links point to).

Not for the top link/description to be for filing an issue/bug relating to _uibuilder_, and for the second link/description to be for filing a bug/issue relating to _Node-RED core_ ?

### Steps To Reproduce

- Go to https://github.com/TotallyInformation/node-red-contrib-uibuilder/issues/new/choose
- Observe the disparity.

### Example Node-RED flow

```
paste your flow here
```

### Environment

- UIBUILDER version: 
- Node-RED version: 
- Node.js version: 
- npm version: 
- Platform/OS: 
- Browser: 

How is Node-RED installed? (globally/locally? admin/user?):

How/where is UIBUILDER installed (palette-manager/globally/locally? Which folder?)

Have you changed any of the `uibuilder` settings in your `settings.js` file?

**Comment by TotallyInformation** [comment]
Hi, many thanks for spotting the typo! A sad case of copy-paste-itus! Will be corrected in uibuilder v7 which hopefully isn't too far away now.
