### ISSUE TITLE
uibuilder reverts to serving files from node_modules folder

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#4]
I copied the files from
.node-red/node_modules/node-red-contrib-uibuilder/nodes/src to
.node-red/uibuilder/uibuilder/src and then slowly morphed them towards
what I eventually need. T one point I made a minor change to the flow and
when I deployed, uibuilder suddenly reverted to running the files in
the original src folder. I confirmed this by tweaking the code there
and saw the change in the output.  If I fiddle about with the flow,
restart node red a few times and so on then it will suddenly start
working again, with exactly the same flow and files as were previously
failing. Even when it was failing I was still seeing the message 'UI
Builder - Local file overrides at
/home/colinl/.node-red/uibuilder/uibuilder' in the log, even though it
appeared not to be using those files.  Nothing else of note in the
logs.
This happened twice in one day but has not happened since so whether it ever happens again remains to be seen.

**Comment by TotallyInformation** [comment]
Thanks Colin. Can you share your flow and front-end code?

**Comment by colinl** [comment]
I don't have the files as they were at the time it failed, I was in the middle of converting it from the sample code provided with the node to something that did what I want. I did not commit it at the time it failed. If or when it goes again I will make sure I commit it at that point.

**Comment by TotallyInformation** [comment]
If you are able to install the version from github (npm install totallyinformation/node-red-contrib-uibuilder, you can add "debug: true" to the uibuilder in settings.js and you will get a file in your userDir called uibuilder.log which will give a lot more information as to what is happening.

**Comment by colinl** [comment]
OK, will do.

**Comment by colinl** [comment]
I haven't had this happen again so am closing this on the assumption it was caused by some hiccup caused by caching or something.

**Comment by TotallyInformation** [comment]
Thanks Colin.
