### ISSUE TITLE
After restarting node-red, the uibuilder node will be lost, and the process will not be able to find the node

### ISSUE THREAD

**Issue by hl0709** [TotallyInformation/node-red-contrib-uibuilder#428]
### Current Behavior

When I create a new process, it is normal to use the svelte-basic template in the uibuilder node to create a view, but when I write the functional code I need, compile npm run build, and restart node-red again, the process will report an error and the process will stop due to the lack of node type. The error message is as follows: {"level":30,"msg":"[node-red-contrib-uibuilder/uibuilder] Error: web.js:serveVendorPackages: pkgDetails.installFolder or pkgDetails.packageUrl is undefined (line:399) ","timestamp":"2024-09-27 10:28:22"}

### Example Node-RED flow

```
paste your flow here
```

### Environment

- UIBUILDER version: v7.0.4
- Node-RED version: v4.0.3
- Node.js version: v18.20.2
- npm version: v10.5.0
- Platform/OS: Windows
- Browser: 

How is Node-RED installed? (globally/locally? admin/user?):

How/where is UIBUILDER installed (palette-manager/globally/locally? Which folder?)

Have you changed any of the `uibuilder` settings in your `settings.js` file?

**Comment by TotallyInformation** [comment]
Hi, thanks for reporting.

When you say that you recompile, I assume that means that you are doing a build on your front-end Svelte code? If that is the case, there shouldn't be any need to restart Node-RED because nothing will have changed on the Node-RED side, only on the front-end (browser) side - all that should be needed is to reload any previously connected page(s).

Can you please confirm?

**Comment by hl0709** [comment]
When I compile and build Svelte, everything is normal, and the browser can access my compiled functions. Only when I restart node-red next time, the process prompts that the uibuilder node cannot be found. As long as I do not restart node-red, everything is normal. And I saw this error message {"level":30,"msg":"[node-red-contrib-uibuilder/uibuilder] Error: web.js:serveVendorPackages: pkgDetails.installFolder or pkgDetails.packageUrl is undefined (line:399 ) ","timestamp":"2024-09-27 10:28:22"} I didn't find the corresponding solution either.

**Comment by TotallyInformation** [comment]
Ah, OK. Can you please check the package.json file that exists in your uibRoot folder (`~/.node-red/uibuilder/package.json` on a standard Node-RED installation).

In that file, you will find a `uibuilder` section and in that, a `packages` section.

I think that one of your installed front-end libraries is missing a critical piece of data and I need to track down which one so I can work out why.

You can post that whole section of the file here if you like, it is not sensitive.

**Comment by hl0709** [comment]
Thank you very much for your answer. This is my package.json file under D:\node-red\nodeRed-Admin\NodeRed\uibuilder.
{
  "version": "7.0.4",
  "name": "uib_root",
  "description": "Root configuration and data folder for uibuilder",
  "scripts": {},
  "homepage": "",
  "bugs": "",
  "author": "",
  "license": "Apache-2.0",
  "repository": "",
  "uibuilder": {
    "packages": {
      "uib_root": {
        "spec": "file:",
        "missing": true,
        "problems": [
          "missing: uib_root@file:, required by uib_root@7.0.4"
        ],
        "latestVersion": null,
        "installedFrom": "file",
        "outdated": {}
      }
    }
  },
  "path": "D:\\node-red\\nodeRed-Admin\\NodeRed\\uibuilder",
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: uib_root@file:, required by uib_root@7.0.4",
    "detail": ""
  },
  "_id": "uib_root@7.0.4",
  "dependencies": {
    "uib_root": "file:"
  }
This is the file D:\node-red\nodeRed-Admin\NodeRed\uibuilder\PlcSvg where I created the process. package.json file in. {
  "name": "svelte-basic",
  "description": "A basic Svelte template for uibuilder and Node-RED.",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "rollup -c --bundleConfigAsCjs --environment NODE_ENV:production",
    "dev": "rollup -c --bundleConfigAsCjs -w --environment NODE_ENV:development",
    "start": "sirv dist --no-clear"
  },
  "devDependencies": {
    "@rollup/plugin-commonjs": "^26.0.1",
    "@rollup/plugin-node-resolve": "^15.0.0",
    "@rollup/plugin-replace": "^5.0.7",
    "@rollup/plugin-terser": "^0.4.4",
    "echarts": "^5.5.1",
    "rollup": "^4.20.0",
    "rollup-plugin-css-only": "^4",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^7.2.0",
    "sirv-cli": "^2.0.0",
    "svelte": "^4.0.0",
    "svelte-echarts": "^1.0.0-rc3"
  },
  "dependencies": {
    "svelte-basic": "file:",
    "svelte-dnd-action": "^0.9.50",
    "svelte-grid": "^5.1.2"
  }
}
There are too many function files. I did not upload the entire svelte-basic file. I compiled according to the svelte-basic template instructions. The only difference is that I introduced external components. I think this should not affect the uibuilder node. No. Find out if you need more information to troubleshoot the issue.

**Comment by TotallyInformation** [comment]
OK, somehow you have added a "library" called `uib_root` and this is what is causing the issue because there is no such library as `uib_root`. You can either remove that using uibuilder's library manager tab or you can manually remove the part of the JSON:

```json
            "uib_root": {
                "spec": "file:",
                "missing": true,
                "problems": [
                    "missing: uib_root@file:, required by uib_root@7.0.4"
                ],
                "latestVersion": null,
                "installedFrom": "file",
                "outdated": {}
            }
```
Then restart node-red. If you do it manually though, please take care to leave the `packages` entry as `packages: {}`.

This should fix the issue and everything should be good.

I have already made some changes to the code for the next release (v7.1) that will handle such a problem more gracefully and give more sensible error information.

**Comment by hl0709** [comment]
I also discovered this problem. This "uib_root" will be added to package.json: {
                "spec": "file:",
                "missing": true,
                "problems": [
                    "missing: uib_root@file:, required by uib_root@7.0.4"
                ],
                "latestVersion": null,
                "installedFrom": "file",
                "outdated": {}
            }This is not something I added myself. Everything is normal when node-red is not restarted. This is what package.json looks like {
  "version": "7.0.4",
  "name": "uib_root",
  "description": "Root configuration and data folder for uibuilder",
  "scripts": {},
  "homepage": "",
  "bugs": "",
  "author": "",
  "license": "Apache-2.0",
  "repository": "",
  "uibuilder": {
    "packages": {}
  },
  "path": "D:\\node-red\\nodeRed-Admin\\NodeRed\\uibuilder",
  "_id": "uib_root@7.0.4",
  "dependencies": {
    "uib_root": "file:"
  }
}
But when I restart node-red it will appear {
  "version": "7.0.4",
  "name": "uib_root",
  "description": "Root configuration and data folder for uibuilder",
  "scripts": {},
  "homepage": "",
  "bugs": "",
  "author": "",
  "license": "Apache-2.0",
  "repository": "",
  "uibuilder": {
    "packages": {
      "uib_root": {
        "spec": "file:",
        "missing": true,
        "problems": [
          "missing: uib_root@file:, required by uib_root@7.0.4"
        ],
        "latestVersion": null,
        "installedFrom": "file",
        "outdated": {}
      }
    }
  },
  "path": "D:\\node-red\\nodeRed-Admin\\NodeRed\\uibuilder",
  "_id": "uib_root@7.0.4",
  "devDependencies": {},
  "peerDependencies": {},
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: uib_root@file:, required by uib_root@7.0.4",
    "detail": ""
  },
  "dependencies": {
    "uib_root": "file:"
  }
}
I manually deleted "uib_root": {
                "spec": "file:",
                "missing": true,
                "problems": [
                    "missing: uib_root@file:, required by uib_root@7.0.4"
                ],
                "latestVersion": null,
                "installedFrom": "file",
                "outdated": {}
            }Restart node-red, the process will still report an error, the uibuilder node cannot be found

**Comment by TotallyInformation** [comment]
OK, please edit that package.json file again. Not only removing the `uib_root` entry from `packages` but also from `dependencies`.

**Comment by hl0709** [comment]
The suggestions you provided are very good. I manually deleted the uib_root packages dependencies in the package.json file and everything returned to normal {
  "version": "7.0.4",
  "name": "uib_root",
  "description": "Root configuration and data folder for uibuilder",
  "scripts": {},
  "homepage": "",
  "bugs": "",
  "author": "",
  "license": "Apache-2.0",
  "repository": "",
  "uibuilder": {
  },
  "path": "D:\\grafana-10.1.4\\node-red\\nodeRed-Admin\\NodeRed\\uibuilder",
  "_id": "uib_root@7.0.4",
  "devDependencies": {},
  "peerDependencies": {},
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: uib_root@file:, required by uib_root@7.0.4",
    "detail": ""
  },
}Restarting node-red no longer reports an error. Thank you for your answer, but I still don’t know where the problem lies. I hope you can correct it in later versions.

**Comment by hl0709** [comment]
The suggestions you provided are very good. I manually deleted the uib_root packages dependencies in the package.json file and everything returned to normal {
  "version": "7.0.4",
  "name": "uib_root",
  "description": "Root configuration and data folder for uibuilder",
  "scripts": {},
  "homepage": "",
  "bugs": "",
  "author": "",
  "license": "Apache-2.0",
  "repository": "",
  "uibuilder": {
  },
  "path": "D:\\node-red\\nodeRed-Admin\\NodeRed\\uibuilder",
  "_id": "uib_root@7.0.4",
  "devDependencies": {},
  "peerDependencies": {},
  "error": {
    "code": "ELSPROBLEMS",
    "summary": "missing: uib_root@file:, required by uib_root@7.0.4",
    "detail": ""
  },
}Restarting node-red no longer reports an error. Thank you for your answer, but I still don’t know where the problem lies. I hope you can correct it in later versions.

**Comment by TotallyInformation** [comment]
Hi, glad it is working.

Nobody has previously reported a similar issue and I don't believe that it is really a bug in the uibuilder code. It looks as though you may have accidentally tried to install something called `uib_root`. The updated error messages should be clearer for anyone finding that kind of issue in the future.
