### ISSUE TITLE
Initial debug information blocks the connection - Edge / 15.15063 W10M

### ISSUE THREAD

**Issue by WKatGitHub** [TotallyInformation/node-red-contrib-uibuilder#49]
Hi,
Beginning with v1.1.0 to v2.0.0, uibuilder displays debug information in the browser console. It's causing some error, which blocks socket.io connection (Edge mobile, node status "connected 0"). After disabling initial debug, uibuilder starts to work, as in previous versions, but when I set Debug Front-End, it's failing again. Debug option in settings.json works fine and saves logs to file.

Without changes it works on:
- PC Edge 18.17763
- PC Firefox and Chrome
- PC IE11 with polyfill.min.js
- mobile Chrome

With this change it works on:
- all above
- PC IE11 without polyfill.min.js
- PC IE11 without polyfill.min.js (checked Debug Front-End)
- Edge 15.15063 W10M (unchecked Debug Front-End)

With this change it fails on:
- Edge 15.15063 W10M (checked Debug Front-End) (after page refresh uibuilder shows status "connected 1" for about 30s)

To turn initial debug off I have changed:
uibuilderfe.js:114
| self.debug = true // do not change directly - use .debug() method
to
| self.debug = false // do not change directly - use .debug() method

uibuilderfe.min.js
| o.debug=!0
to
| o.debug=0

Software       | Version
-------------- | -------
Node.JS        |  8.15.1
npm            |  6.9.0
Node-RED       |  0.19.6 installed in home/user/.node-red
uibuilder node | 2.0.0 (1.1.0 / 1.2.1)
uibuilderFE    | 2.0.0 (1.1.0 / 1.2.1)
OS             |  Linux 4.14.98-v7+ arm LE (Raspbian Stretch RPI3B+)
Browser        | Edge 15.15063 W10M Lumia640

**Comment by TotallyInformation** [comment]
Hi, many thanks for reporting this.

You can turn on/off debugging in the browser using either the switch in the Node-RED admin ui for the instance of uibuilder. Or you can turn it on/off from your index.js file which should override the setting sent from Node-RED.

Are you saying that even turning front-end debugging off using one of the above methods, you are still getting an error in the WM10 version of Edge?

I've just tried uibuilder 1.2 with IE11 and I can see this error in the console:

```
SCRIPT438: Object doesn't support property or method 'endsWith'
uibuilderfe.min.js (1,596)
```

Which is expected. Polyfill will fix that.

However, in uibuilder v2, that is fixed as I've included a pollyfill for `endsWith` so it shouldn't fail.  I've just tested that with IE11 and it works fine.

Unfortunately, I don't currently have an active WM10 device to try this on as I no longer use them. However, if you take the latest build of v2, it should work. 

Can you test and let me know? Please make sure to start with a clean instance of a uibuilder node.

Thanks.

**Comment by WKatGitHub** [comment]
Hi, thanks for the quick response.
> Are you saying that even turning front-end debugging off using one of the above methods, you are still getting an error in the WM10 version of Edge?

Yes, even if Debug is turned off in all possible places. 
Interesting is that on PC IE11 without mentioned modification, after browser restart, console output is:
` undefined "uibuilder"`. But after 10-20 minutes of browser idle, it's starting to work.
 
No problem I will check the default config.

**Comment by TotallyInformation** [comment]
OK, I can push a fix for the `endsWith` issue to v1 if you think it is worth while. I'm trying to get v2 out of the door but I'm trying to make sure that I've done as many breaking changes as possible in this version so people don't keep having to tweak things.

Hopefully you will find v2 a nice upgrade, it is somewhat more efficient and you will get more flexibility. I'm about to push another set of changes to v2 so do update from time-to-time.

**Comment by WKatGitHub** [comment]
I will stay at v2. I found that .apply() don't work with console.* . 
Tested examples (change in the self.uiDebug function ):
`Math.max.apply(null, [10, -1, 5]) // works`
`console[type]([].slice.call(arguments, 1)) // works`
`console[type].apply(undefined, ['test']) // fails`

**Comment by TotallyInformation** [comment]
Great, thanks for this! I will look to updating v2 with that. Very helpful.

**Comment by TotallyInformation** [comment]
I've pushed a fix for the IE11 missing endsWith - v1.2.2

**Comment by WKatGitHub** [comment]
Thanks, in IE11 I used mainly the console, due to problems with remote debugging Edge on Lumia 640. Thank you for developing this project. It is a very useful and flexible node.

**Comment by TotallyInformation** [comment]
Applied to v2. Sorry about the delay. Closing this now.
