### ISSUE TITLE
uibuilder always passing on messages received irrespective of setting

### ISSUE THREAD

**Issue by colinl** [TotallyInformation/node-red-contrib-uibuilder#5]
Using version 0.3.5 from git any received messages are immediately passed on irrespective of the setting of  "Forward recieved(sp?) messages direct to output?"
In the log file I see messages
debug:  name=, topic=, url=home, fwdIn=true, custFldrs=true
and
debug: uibuilder - msg passed downstream to next node:  _msgid=49ee617.2411da, topic=uibuilder, payload=1505920798297
whatever the setting.

**Comment by colinl** [comment]
I think possibly line 116 of uibuilder.js
node.fwdInMessages = config.fwdInMessages || true
hasn't been fully thought through :)
I think possibly the next line also.

**Comment by TotallyInformation** [comment]
Now you are just showing off! ;-)

You are correct. Please feel free to change manually and I will fix in v0.3.6 which is next to be pushed up along with other fixes such as the suggested front-end namespace fix & the improvement to the module location find.

Actually the default for `customFoldersReqd` *is* correct as it matches the default in the editor. Though you could argue that the editor has the wrong default perhaps. Please feel free to put that argument through if you like :)

**Comment by TotallyInformation** [comment]
Added a shout out to you in the readme - thanks for your testing and suggestions.

**Comment by colinl** [comment]
I think it is more than that, unless I am missing something. If the box is not checked will not config.fwdInMessages be false? If so then that line will always set the node variable to true. The same is true for the next line, if the box is not checked then node.customFoldersReqd will still be set true.

**Comment by TotallyInformation** [comment]
They should always have values actually as uibuilder.html sets defaults. false for fwd and true for the folder. But let me test.

**Comment by colinl** [comment]
So that means both those lines are wrong, as whether the checkbox is ticked or not they will always set the node.variables to true.

**Comment by TotallyInformation** [comment]
Oops, I shouldn't try to fix problems when I'm supposed to be finishing work! I'll have another look this evening.

**Comment by TotallyInformation** [comment]
OK, now I'm home, I've retested I had to take the defaults off in `uibuilder.js`. They shouldn't be needed anyway. Also fixed up the local folder switch which wasn't quite working correctly. 

I've pushed up v0.3.7 for you to try.

**Comment by colinl** [comment]
Tested OK
