### ISSUE TITLE
socket.io not available

### ISSUE THREAD

**Issue by justcsdr** [TotallyInformation/node-red-contrib-uibuilder#53]
After the last update all the requests are going to "/<httpNodeRoot value>/uibuilder/socket.io/?....." but socket.io is at "/uibuilder/socket.io/?....."

**Comment by TotallyInformation** [comment]
Drat, looks like I messed up with the last update. I will try to fix this weekend, family commitments permitting.

**Comment by TotallyInformation** [comment]
Hi, sorry about the delay. Push now fixed. v1.2.6

Please note that you must change the reference to socket.io in your `index.html` file to:

```
<script src="../uibuilder/socket.io/socket.io.js"></script>
```

e.g. the URL must start with double dots.
