### ISSUE TITLE
Node Red OPCUA error when installing

### ISSUE THREAD

**Issue by vysakhraj** [TotallyInformation/node-red-contrib-uibuilder#56]
Hi All,

I am facing an issue when I try to install OPCUA node in Node Red... Below is the message I am getting when I try to install it. Can someone please tell me why this is happening and how can I solve it ?

root@iot2000:~# npm install node-red-contrib-opcua
npm ERR! Linux 4.4.105-cip15
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "node-red-contrib-opcua"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code EAI_AGAIN
npm ERR! errno EAI_AGAIN
npm ERR! syscall getaddrinfo

npm ERR! getaddrinfo EAI_AGAIN registry.npmjs.org:443
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/root/npm-debug.log

**Comment by colinl** [comment]
That error suggests a network connectivity issue.
Also note that you are using an ancient version of npm (current is 6.x) and node (minimum recommended is now 8.x and 6.x was never a supported version).
Further, is this anything to do with uibuilder.  You might be better to ask for help on the node red forum
https://discourse.nodered.org/

**Comment by vysakhraj** [comment]
Thank you @colinl for the reply. :)

**Comment by TotallyInformation** [comment]
`EAI_AGAIN` means the DNS server replied that it cannot currently fulfill the request.

So you need to check your DNS server settings on the device where you are trying to install the node.

Definitely not a uibuilder issue I'm happy to report. If you have other issues like this, do feel free to raise them in the Node-RED forum.
