### ISSUE TITLE
RangeError: Maximum call stack size exceeded crashes Node-RED in endless loop at startup.

### ISSUE THREAD

**Issue by bahijmansour-iotech** [TotallyInformation/node-red-contrib-uibuilder#63]
### Software and Package Versions
Software       | Version
-------------- | -------
Node.JS        |  10.15.3
npm            | 6.11.2
Node-RED       | 0.20.7
uibuilder node | not shown but not latest
uibuilderFE    | not shown but not latest
OS             | Raspbian GNU/Linux (stretch) 
Browser        | Chrome Version 76.0.3809.100 (Official Build) (64-bit)

### How is Node-RED installed? Where is uibuilder installed?
Installed with Node-RED admin interface "Manage Palette". 

Not sure if this was fixed in latest uibuilder version. But graceful-fs node-module caused Node-RED to endlessly crash when starting `node-red-start` and crash as soon as editor endpoint at http://localhost:1880 was reached through browser after using `node-red --safe`. 

Screenshot of startup. 

![image](https://user-images.githubusercontent.com/52288559/64025247-2f12a600-cb34-11e9-8078-17f543a59860.png)

Screenshot with [warn] log after graceful-fs module removed.
![image](https://user-images.githubusercontent.com/52288559/64025341-62553500-cb34-11e9-834f-ae60067b7b03.png)

I have updated uibuilder to latest and can see graceful-fs installed no issues till now.

**Comment by TotallyInformation** [comment]
So uibuilder is working OK now that you have updated to the current version or not?

I am using node.js v10.15.3 on Windows so hard to see that would be the issue & nobody else has reported an issue either. Also, graceful-fs is used by some other nodes.

If you aren't working, can you please run the command `npm ls graceful-fs` from your userDir folder and report back the output? And could you also please let me have a list of other nodes you have installed?

**Comment by bahijmansour-iotech** [comment]
Output of `npm ls graceful-fs`: 
![image](https://user-images.githubusercontent.com/52288559/64105408-17266680-cd6e-11e9-9cd6-b99044864ca2.png)

List of nodes installed: 
`{  
   "node-red":{  
      "version":"0.20.7",
      "nodes":[  
         "batch",
         "catch",
         "change",
         "comment",
         "csv",
         "debug",
         "delay",
         "exec",
         "file",
         "file in",
         "function",
         "html",
         "http in",
         "http proxy",
         "http request",
         "http response",
         "inject",
         "join",
         "json",
         "link in",
         "link out",
         "mqtt in",
         "mqtt out",
         "mqtt-broker",
         "range",
         "rpi-gpio in",
         "rpi-gpio out",
         "rpi-keyboard",
         "rpi-mouse",
         "sort",
         "split",
         "status",
         "switch",
         "tcp in",
         "tcp out",
         "tcp request",
         "template",
         "tls-config",
         "trigger",
         "udp in",
         "udp out",
         "unknown",
         "watch",
         "websocket in",
         "websocket out",
         "websocket-client",
         "websocket-listener",
         "xml",
         "yaml"
      ]
   },
   "node-red-contrib-auth":{  
      "version":"0.1.7",
      "nodes":[  
         "JsonWebToken",
         "JsonWebToken_config"
      ]
   },
   "node-red-contrib-config":{  
      "version":"1.1.2",
      "nodes":[  
         "config"
      ]
   },
   "node-red-contrib-firebase":{  
      "version":"1.1.1",
      "nodes":[  
         "firebase auth",
         "firebase config",
         "firebase modify",
         "firebase ondisconnect",
         "firebase.on",
         "firebase.once"
      ]
   },
   "node-red-contrib-fs-ops":{  
      "version":"1.5.0",
      "nodes":[  
         "fs-ops-access",
         "fs-ops-copy",
         "fs-ops-delete",
         "fs-ops-dir",
         "fs-ops-link",
         "fs-ops-mkdir",
         "fs-ops-mktmpdir",
         "fs-ops-move",
         "fs-ops-size",
         "fs-ops-stats",
         "fs-ops-type"
      ]
   },
   "node-red-contrib-http-multipart":{  
      "version":"0.3.2",
      "nodes":[  
         "httpInMultipart"
      ]
   },
   "node-red-contrib-ibm-watson-iot":{  
      "version":"0.2.8",
      "nodes":[  
         "wiotp in",
         "wiotp out",
         "wiotp-credentials"
      ]
   },
   "node-red-contrib-md5":{  
      "version":"1.0.4",
      "nodes":[  
         "md5"
      ]
   },
   "node-red-contrib-moment":{  
      "version":"3.0.3",
      "nodes":[  
         "humanizer",
         "moment"
      ]
   },
   "node-red-contrib-npm":{  
      "version":"1.0.2",
      "nodes":[  
         "npm"
      ]
   },
   "node-red-contrib-play-audio":{  
      "version":"2.3.2",
      "nodes":[  
         "play audio"
      ]
   },
   "node-red-contrib-timeout":{  
      "version":"1.1.1",
      "nodes":[  
         "timeout"
      ]
   },
   "node-red-contrib-ui-heatmap":{  
      "version":"1.1.1",
      "nodes":[  
         "heat-map"
      ]
   },
   "node-red-contrib-ui-svg":{  
      "version":"1.0.0",
      "nodes":[  
         "ui_svg_graphics"
      ]
   },
   "node-red-contrib-uibuilder":{  
      "version":"2.0.1",
      "nodes":[  
         "uibuilder"
      ]
   },
   "node-red-contrib-web-worldmap":{  
      "version":"1.5.31",
      "nodes":[  
         "worldmap",
         "worldmap in",
         "worldmap-tracks"
      ]
   },
   "node-red-dashboard":{  
      "version":"2.14.0",
      "nodes":[  
         "ui_audio",
         "ui_base",
         "ui_button",
         "ui_chart",
         "ui_colour_picker",
         "ui_date_picker",
         "ui_dropdown",
         "ui_form",
         "ui_gauge",
         "ui_group",
         "ui_link",
         "ui_numeric",
         "ui_slider",
         "ui_spacer",
         "ui_switch",
         "ui_tab",
         "ui_template",
         "ui_text",
         "ui_text_input",
         "ui_toast",
         "ui_ui_control"
      ]
   },
   "node-red-node-email":{  
      "version":"1.6.3",
      "nodes":[  
         "e-mail",
         "e-mail in"
      ]
   },
   "node-red-node-feedparser":{  
      "version":"0.1.14",
      "nodes":[  
         "feedparse"
      ]
   },
   "node-red-node-ledborg":{  
      "version":"0.0.21",
      "nodes":[  
         "ledborg"
      ]
   },
   "node-red-node-pi-sense-hat":{  
      "version":"0.0.18",
      "nodes":[  
         "rpi-sensehat in",
         "rpi-sensehat out"
      ]
   },
   "node-red-node-ping":{  
      "version":"0.0.16",
      "nodes":[  
         "ping"
      ]
   },
   "node-red-node-random":{  
      "version":"0.1.2",
      "nodes":[  
         "random"
      ]
   },
   "node-red-node-rbe":{  
      "version":"0.2.5",
      "nodes":[  
         "rbe"
      ]
   },
   "node-red-node-sentiment":{  
      "version":"0.1.4",
      "nodes":[  
         "sentiment"
      ]
   },
   "node-red-node-serialport":{  
      "version":"0.7.1",
      "nodes":[  
         "serial in",
         "serial out",
         "serial request",
         "serial-port"
      ]
   },
   "node-red-node-smooth":{  
      "version":"0.1.0",
      "nodes":[  
         "smooth"
      ]
   },
   "node-red-node-sqlite":{  
      "version":"0.3.6",
      "nodes":[  
         "sqlite",
         "sqlitedb"
      ]
   },
   "node-red-node-swagger":{  
      "version":"0.1.8",
      "nodes":[  
         "swagger-doc"
      ]
   },
   "node-red-node-tail":{  
      "version":"0.0.2",
      "nodes":[  
         "tail"
      ]
   },
   "node-red-node-twitter":{  
      "version":"1.1.5",
      "nodes":[  
         "twitter in",
         "twitter out",
         "twitter-credentials"
      ]
   }
}`

**Comment by TotallyInformation** [comment]
And is uibuilder working now?

**Comment by bahijmansour-iotech** [comment]
Working fine now.

**Comment by TotallyInformation** [comment]
Just to note that someone raised a similar issue in the forum. However, that wasn't related to uibuilder so it looks like this issue is only indirectly related to uibuilder.

The common factor actually seems to be node-red-contrib-npm

https://discourse.nodered.org/t/random-crashes-with-maximum-call-stack-size-exceeded/15099/3
