### ISSUE TITLE
Cannot read property 'endsWith' of undefined in uibuilderfe.js

### ISSUE THREAD

**Issue by scottpageindysoft** [TotallyInformation/node-red-contrib-uibuilder#73]
Software       | Version
-------------- | -------
Node.JS        | 10.16.3
npm            | 6.11.3
Node-RED       | 1.0.0
uibuilder node | 2.0.4
uibuilderFE    | 
OS             |  linux (Docker - node:lts - as of 03-OCT-2019 MST)
Browser        | Chrome 77.0.3865.90 (Official Build) (64-bit)
Vue                |  2.6.10

### How is Node-RED installed?   Docker - node-red:latest
Where is uibuilder installed?
npm package:  <node-red-base-folder>/node_modules/node-red-contrib-uibuilder
uibuilder node:  <node-red-base-folder>/projects/visualcal-node-red-dev/uibuilder/visualcal

**ISSUE**

I made contact with you originally [here](https://discourse.nodered.org/t/is-vuetify-compatible-with-uibuilder/16222), yesterday on the node-red forum.

Per that forum thread, I was getting an error in the Chrome console during run-time.
The error:  `Cannot read property 'endsWith' of undefined , in uibuilderfe.js`

I'm using @vue/cli 3, and I'm proud to say I got it working with uibuilder.  However, I'm uncertain if using the vue cli may be causing the issue.

What I do know is that when I changed lines 105 and 165 in uibuilderfe.js, the error went away.

Here's the fixes for those lines:
105:  `if (u.length > 0) {
    if (u[u.length - 1].endsWith('.html')) u.pop()
}`
165:  `if (fullPath.length > 0) {
    if (fullPath[fullPath.length - 1].endsWith('.html')) fullPath.pop()
}`

I got an additional error concerning sockets.io and "<" symbol, but I'll open a separate issue for that, and I already have a fix.

I also have a fully running version using vue/cli 3, so I'll add a repository and link it so others can check it out.

Thanks!

**Comment by TotallyInformation** [comment]
Fix will be in v2.0.5 - hopefully will be released this weekend.

**Comment by TotallyInformation** [comment]
v2.0.5 published to npm
