### ISSUE TITLE
I reinstalled UIBUILDER and this "Really Simple Example Quote of the day"

### ISSUE THREAD

**Issue by youngkzy** [TotallyInformation/node-red-contrib-uibuilder#76]
As it turns out, you put the text in the box and THEN you CLICK on the BUTTON !!  

 Aaaaaaah !  I see.....

**Comment by TotallyInformation** [comment]
Is there an issue here or not?

**Comment by TotallyInformation** [comment]
Doesn't appear to be an issue so closing.
