### ISSUE TITLE
JQuery example: Nosniff on FF, strict MIME on Chrome

### ISSUE THREAD

**Issue by j2l** [TotallyInformation/node-red-contrib-uibuilder#80]
First of all, thanks, I'm starting to discover how great is your module!
I try it on a ROCK64 o nthe LAN.

### Software and Package Versions
Software       | Version
-------------- | -------
Node.JS        | v13.2.0
npm            | 6.13.1
Node-RED       | 1.0.3
uibuilder node | 2.0.6
uibuilderFE    | ??
OS             | DietPi (Debian), Raspberry ARM64 4GB RAM
Browser        | Win10, FF 70.0.0.1, Chrome 78.0.3904.108 (Official Build) (64-bit)

### How is Node-RED installed? Where is uibuilder installed?
dietpi-software, to get node-red as a service
uibuilder installed using the Node-Red Palette

Uibuilder default Vue is working fine but when I imported JQuery example then pasted html, css and js from https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Example:-JQuery 
/jq correctly throws:
```
 Welcome to UIbuilder for Node-RED
This is an example of using uibuilder with jQuery.
...
```
but the Console of firefox sents:
```
La ressource à l’adresse « http://192.168.1.25:1880/uibuilder/vendor/normalize.css/normalize.css » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
jq
La ressource à l’adresse « http://192.168.1.25:1880/uibuilder/vendor/jquery/dist/jquery.min.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
jq
La ressource à l’adresse « http://192.168.1.25:1880/uibuilder/vendor/normalize.css/normalize.css » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
jq
La ressource à l’adresse « http://192.168.1.25:1880/uibuilder/vendor/jquery/dist/jquery.min.js » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).
jq
Échec du chargement pour l’élément <script> dont la source est « http://192.168.1.25:1880/uibuilder/vendor/jquery/dist/jquery.min.js ». jq:52:1
ReferenceError: $ is not defined
```
and Chrome
```
192.168.1.25/:1 Refused to apply style from 'http://192.168.1.25:1880/uibuilder/vendor/normalize.css/normalize.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
jquery.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:24 Uncaught ReferenceError: $ is not defined
    at index.js:24
init.js:298 autorefresh_option true
192.168.1.25/:1 Refused to apply style from 'http://192.168.1.25:1880/uibuilder/vendor/normalize.css/normalize.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

But I double checked the file MIME type in uibuilder is fine:
![image](https://user-images.githubusercontent.com/65325/69545240-afa93d00-0f91-11ea-9da8-e5b82e0d6b48.png)

Any idea?

**Comment by j2l** [comment]
It works if I use /uibuilder and paste index.html and index.js content.
Really weird that .uibuilder is hard-coded-related to MIME type. I don't get it.

**Comment by j2l** [comment]
BTW I checked user and everything is fine in /jq land:
```
/mnt/dietpi_userdata/node-red/uibuilder/jq/src# ls -al
total 36
drwxr-xr-x 2 nodered nodered 4096 Nov 25 13:14 .
drwxr-xr-x 4 nodered nodered 4096 Nov 25 13:14 ..
-rw-r--r-- 1 nodered nodered  516 Oct 26  1985 .eslintrc.json
-rw-r--r-- 1 nodered nodered   77 Nov 25 13:21 index.css
-rw-r--r-- 1 nodered nodered 2867 Nov 25 14:17 index.html
-rw-r--r-- 1 nodered nodered 4652 Nov 25 13:59 index.js
-rw-r--r-- 1 nodered nodered  358 Oct 26  1985 manifest.json
-rw-r--r-- 1 nodered nodered 1152 Oct 26  1985 uibuilder.appcache

```

**Comment by TotallyInformation** [comment]
Hi, uibuilder isn't hard-coded to anything in terms of mime. 

> Refused to apply style

You get that because of the way that Node-RED works with ExpressJS to deliver web services. To avoid it, you need to make sure that you use `<link type="text/css" rel="stylesheet" ...` in your html.

The clue is in the message: `X-Content-Type-Options: nosniff`

ExpressJS isn't allowing the browser to "sniff" out the content type so you have to be explicit. The same would be true for javascript if you've included it as a link in the head. Including js as `<script>` tags in the body is already explicit and so you don't need to specify that it is JavaScript since that is the default language for script tags.

**Comment by j2l** [comment]
Thanks @TotallyInformation I simply followed https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Example:-JQuery , I only pasted your code.
The same code works with /uibuilder, not /jq

**Comment by j2l** [comment]
thanks @TotallyInformation I wonder why it worked with /uibuilder though.
I still receive:
`La ressource à l’adresse « http://192.168.1.25:1880/uibuilder/vendor/normalize.css/normalize.css » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff)`
Because normalize.css is nowhere on the disk:
`locate --regex uibuilder.+normalize` shows nothing

**Comment by TotallyInformation** [comment]
> I only pasted your code

Yes, it was incorrect I'm afraid. It used to work but some update of Node-RED/ExpressJS tightened up the rules it seems.

> Because normalize.css is nowhere on the disk

You will need to install the normalize package or use it from a CDN. You can use the package manager built into uibuilder to install it if you want to.

**Comment by j2l** [comment]
Oh, I see. I added jquery but thought normalize.css was a css sheet, not a package.
Thank you again @TotallyInformation 
It works without error now :)
