### ISSUE TITLE
Socket not connected when behind proxy

### ISSUE THREAD

**Issue by vinaykharecha** [TotallyInformation/node-red-contrib-uibuilder#84]
### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | v12.13.0
npm            | v6.12.0
Node-RED       | v1.0.3
uibuilder node |  v2.0.6
uibuilderFE    | v2.0.6
OS             | Raspbian
Browser        | Chrome v79.0.3945.117

### Issue

I have node-red running behind HA proxy to access it over the internet, however when I access default uibuilder page over HA proxy than it says socket connection false and no message are sent or received from uibuilder node. just to be clear that there is no issue with HA Proxy node-red-dashboard is able to make socket connection without any issue.

When I access locally i.e. without proxy than socket connection works

HA Proxy is configured following way in my case

> domain.com/node-red/uibuilder/ -> localhost:1880/uibuilder/

I see the following message in the network tab of chrome

> 41:44/node-red/uibuilder,"Invalid namespace"

**Comment by TotallyInformation** [comment]
Hi, although I don't use HAproxy myself, some quick searches online threw up some configurations recommended for use with websockets that seem somewhat more complex than yours.

Are you able to change the settings to align with those recommendations?

**Comment by vinaykharecha** [comment]
@TotallyInformation , Yes I already have a configuration for WebSockets in HA proxy and as I said WebSockets connection of node-red-dashboard is working fine with HA proxy and i am pretty sure issue is not related to HA proxy configuration. my HA proxy configuration is as below just for reference.

```HAProxy
global
    log 127.0.0.1 local1 notice

    tune.ssl.default-dh-param 2048
    maxconn 9999
    maxpipes 9999
    nbproc 3
    cpu-map 1 0
    cpu-map 2 1
    cpu-map 3 2
    daemon

    ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA
    ssl-default-server-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    option  forwardfor
    option  http-keep-alive

    timeout connect 10s
    timeout client 10s
    timeout server  30m

    # Long timeout for WebSocket connections.
    timeout tunnel 2h
    default-server init-addr last,libc,none
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    bind *:80

    acl is_dataplicity_domain hdr(host) -i xxxx.dataplicity.io
    acl is_path_webserver path_beg /webserver
    acl is_path_node_red path_beg /node-red
    acl is_path_rabbitmq path_beg /rabbitmq

    use_backend webserver if is_dataplicity_domain is_path_webserver
    use_backend node_red if is_dataplicity_domain is_path_node_red
    use_backend rabbitmq if is_dataplicity_domain is_path_rabbitmq

    default_backend ha_stats

backend webserver
    reqrep ^([^\ ]*\ /)webserver[/]?(.*)     \1\2
    balance leastconn
    timeout server 30m
    timeout connect 10s
    server webserver_01 192.168.31.126:3033 check

backend node_red
    reqrep ^([^\ ]*\ /)node-red[/]?(.*)     \1\2
    balance leastconn
    timeout server 30m
    timeout connect 10s
    server node_red_01 192.168.31.126:1880 check

backend rabbitmq
    reqrep ^([^\ ]*\ /)rabbitmq[/]?(.*)     \1\2
    balance leastconn
    timeout server 30m
    timeout connect 10s
    server rabbitmq_01 192.168.31.126:15672 check

backend ha_stats
    balance leastconn
    server ha_stats_01 0.0.0.0:50000

listen stats
  bind *:50000
  mode http
  stats enable
  stats hide-version
  stats realm Haproxy\ Statistics
  stats uri /
  stats auth xxxx:xxxxxx
```

**Comment by TotallyInformation** [comment]
But that config doesn't include the things that others seem to be saying that may be required for correct operation of websockets. While it may work for some things, I don't know if it works for everything.

https://www.startpage.com/do/dsearch?query=haproxy+websockets&cat=web&pl=opensearch&language=english

I assume that you've tried accessing your uibuilder app from within your network and that is working OK?

Anyway, before we go down that rabbit hole, lets get some more info from the browser.

I need the output from the following commands - you can do these from the developer console:

```
uibuilder.get('ioNamespace')
uibuilder.get('ioPath')
uibuilder.get('httpNodeRoot')
uibuilder.get('url')
window.location.pathname
```

**Comment by vinaykharecha** [comment]
@TotallyInformation , configuration for each use case would be different, those are link mention about load balancing of the socket which does not apply in my case.

```JavaScript
uibuilder.get('ioNamespace')
// Output: "/node-red/uibuilder"

uibuilder.get('ioPath')
// Output: "/node-red/uibuilder/vendor/socket.io"

uibuilder.get('httpNodeRoot')
// Output: "/node-red"

uibuilder.get('url')
// Output: "uibuilder"

window.location.pathname
// Output: "/node-red/uibuilder/"
```

I think the issue is because of trailing slash missing on ioNamespace whereas window.location.pathname has it.

**Comment by TotallyInformation** [comment]
No, it is meant to have no trailing slash.

Here are my settings:
![image](https://user-images.githubusercontent.com/1591850/73123674-10e98e80-3f8a-11ea-8796-7fcb4f4333d6.png)

One other bit of info. Can you please have a look at the cookie that any of your network requests should have attached. This is a cookie set by uibuilder on the Node-RED server and it should also contain the namespace. We need to make sure that the two match.

My suspicion is that the front-end library, in trying to calculate the expected namespace, is calculating it incorrectly because of the URL rewriting that the proxy is doing.

**Comment by vinaykharecha** [comment]
Ohh I see.

I can see three cookies on my end as following
![Screenshot 2020-01-25 at 11 23 29 PM](https://user-images.githubusercontent.com/11410214/73125233-883f1280-3fca-11ea-990b-139edea27118.png)


One more thing I noticed is that, I see three types of socket request keep repeating on and on with following responses
![Screenshot 2020-01-25 at 11 27 32 PM](https://user-images.githubusercontent.com/11410214/73125251-c5a3a000-3fca-11ea-96d6-eb88ea91ee4e.png)
![Screenshot 2020-01-25 at 11 28 04 PM](https://user-images.githubusercontent.com/11410214/73125255-d3592580-3fca-11ea-9e90-72f152b03b3e.png)
![Screenshot 2020-01-25 at 11 28 17 PM](https://user-images.githubusercontent.com/11410214/73125256-d8b67000-3fca-11ea-8315-221514d36c21.png)

**Comment by TotallyInformation** [comment]
Any chance you could temporarily install v2.0.7 from GitHub? I think it may fix the issue but I can't test at my end.

**Comment by vinaykharecha** [comment]
@TotallyInformation , Yup that totally worked like a breeze :)
Thank you very much for all your efforts in fixing this issue.

**Comment by TotallyInformation** [comment]
No problem, I'll push v2.0.7 out now. Should be available in Node-RED's palette manager within the hour.
