### ISSUE TITLE
StackedBarChart

### ISSUE THREAD

**Issue by Luppakorva** [TotallyInformation/node-red-contrib-uibuilder#85]
Heyas,

I'm having trouble trying to get stackedBarChart created with chart.js 

What I'm doing in .onChange is:

`vueApp.barChartData.push( new Array(newVal.payload[0].topic, newVal.payload[0].data[0].value, newVal.payload[0].data[0].value2))`

But the second value (value2) is not taking any effect. Any chance someone could help a bit how to get this done so that I can use stacked bars or is it even possible?

**Comment by TotallyInformation** [comment]
Hi, this is the issues list for uibuilder. I'm afraid that I can't really answer loads of questions about specific VueJS components here as I may not be using any of them (there are also thousands). It also makes it hard to track real issues with uibuilder.

I would recommend asking in whatever support forum chart.js may provide.

I assume that you have chart.js working with uibuilder having used the article in the WIKI or the Node-RED flows site? If so, clearly uibuilder is working ok.

All I can advise is that you double check `newVal.payload` to make sure its structure is actually what you think it is.

**Comment by Luppakorva** [comment]
Understood, thanks for the info!
