### ISSUE TITLE
Vendor Client Libraries

### ISSUE THREAD

**Issue by fineemb** [TotallyInformation/node-red-contrib-uibuilder#87]
Before logging an issue, please make sure that you are either on the latest npm version or the latest GitHub version.

Please ensure that as much of the following information is included as possible.

### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 10.18.1
npm            |  6.13.4
Node-RED       | 1.0.3
uibuilder node | 2.0.7
uibuilderFE    | 
OS             | windows 10
Browser        | chrome

### How is Node-RED installed? Where is uibuilder installed?

Node-RED installed:  docker
uibuilder: Palette
### Url cannot be mapped correctly

![01](https://user-images.githubusercontent.com/16739914/75436076-edea3a00-598e-11ea-94b8-53f71105ec69.jpg)
![01](https://user-images.githubusercontent.com/16739914/75436312-51746780-598f-11ea-9534-f866e36104de.jpg)
![01](https://user-images.githubusercontent.com/16739914/75436539-b465fe80-598f-11ea-92fa-930bab24469c.jpg)

**Comment by TotallyInformation** [comment]
Hi, this is primarily an issue with the `@polymer\iton-icons` package, not with uibuilder.

If you check the `package.json` file for that package, you will note that it does not have a `main` property defined which means that uibuilder has no idea what is meant to be the core javascript file for the package.

Having said that, it shouldn't have left the system folder as `/data`.

As a poor temporary work-around, you should, I think, find the icons served from `../uibuilder/vendor/@polymer/iron-icons/@node_modules/@polymer/iron-icons` !!!

I will investigate when I get an hour or so free.
