### ISSUE TITLE
Moon.js not showing values

### ISSUE THREAD

**Issue by Patriciawa** [TotallyInformation/node-red-contrib-uibuilder#92]
Software       | Version
-------------- | -------
Node.JS        | v12.17.0
npm            | 6.14.5
Node-RED       | 1.0.6
uibuilder node | 2.0.7
uibuilderFE    | ?
OS             | Raspberry Pi OS (3B+)
Browser        | Chrome 83

Hi,
I'm having a weird issue that I can't figure out on my own, any help is appreciated, basically the dashboard isn't showing any values when using moon.js. When using the standard template that comes pre-installed I can see all the messages.

I have installed it via npm, but reinstalled it via the admin of node-red. Installed in the standard directory (.node-red/uibuilder & .node-red/node_modules/node-red-contrib-uibuilder)

Now I tried to use Moon.js via the following example: [Example Show MQTT device info using Moon with caching](https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/Example-Show-MQTT-device-info-using-Moon-with-caching). However I can't see any values, see the screen shot;

![image](https://user-images.githubusercontent.com/49994443/85015329-14afc480-b168-11ea-8ef7-9e8854636686.png)

Upon inspecting I noticed the following:

![image](https://user-images.githubusercontent.com/49994443/85015435-41fc7280-b168-11ea-9175-efe438b9fcc3.png)

I have installed the library via the Front-End Library Manager, but it seems that it can't find it.
![image](https://user-images.githubusercontent.com/49994443/85015906-15952600-b169-11ea-8eaf-92f4899c615d.png)
Looks ok right?

Regards, 
Patrick

**Comment by TotallyInformation** [comment]
Sorry about the delay getting back on this one.

The reason you are having problems is that the example comes from uibuilder v1. In v2 there were a load of breaking changes, notably the URL's changed slightly. So you need to translate from the old to new URL's and then you will also need to add a `uibuilder.start()` function call.

The details are here: 

https://github.com/TotallyInformation/node-red-contrib-uibuilder/wiki/v2-Breaking-Changes

**Comment by Patriciawa** [comment]
edited documentation
