### ISSUE TITLE
Expanding editor on iOS does not work as expected.

### ISSUE THREAD

**Issue by boisei0** [TotallyInformation/node-red-contrib-uibuilder#93]
When expanding the editor (for editing files) when working on an iOS device (iPad pro 11 inch), the view is supposedly set to full screen. This does not appear to work on Safari 13 with iOS devices. While the height is set to the full available height, the width isn't set, and regardless of that, Safari does what Safari wants to do...

ACE editor on Node-RED 1.0.6:
![4FB16389-3291-4779-8BBF-CC2EC0577919](https://user-images.githubusercontent.com/1899092/85029465-9873ac00-b17c-11ea-9474-dbddab0b7e18.jpg)
Monaco editor on Steve's Monaco branch, Node-RED 1.1.0-dev, split view with terminal:
![BF162736-AB59-4284-B772-C9E96DE4C1ED](https://user-images.githubusercontent.com/1899092/85029472-9ad60600-b17c-11ea-81fa-6163e528c03c.png)

Relevant code that handles setting to full screen:
https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/84a9db668c3d47ce643177b66979025e11122fbb/node-admin-src/script.js#L710-L727
Relevant code that handles the resizing:
https://github.com/TotallyInformation/node-red-contrib-uibuilder/blob/84a9db668c3d47ce643177b66979025e11122fbb/node-admin-src/script.js#L409-L437

### Solution
I think what "caused" this is the more or less homegrown solution to expand to full screen in the browser, rather than use the Node-RED core's approach to start a full width editor on another panel, one stack level higher. For example, see the function node or template's node approach for that. I'm working on a fix based on that. Since the available options for file format are identical to those of the template node, the default `_text` typeEditor can be used, which supports all these options. 

https://github.com/node-red/node-red/blob/708620f929199b392c5a30cae502b540f94546d0/packages/node_modules/%40node-red/nodes/core/function/80-template.html#L115-L133

If needed for how the `uiace` variables are used and the need for saving/loading of files, a similar typeEditor can be defined either way, but I believe the default `_text` type would do for uibuilder's usage.

### Software and Package Versions

Software       | Version
-------------- | -------
Node.JS        | 12 LTS
npm            | 6.14.5
Node-RED       | 1.0.6 / 1.1.0 beta
uibuilder node | 2.0.7
uibuilderFE    | 2.0.7
OS             | Installed on Pi 4 with Ubuntu 20.04 LTS (64bit), viewed on iPad Pro 2nd generation running iOS 13.5
Browser        | Safari 13

### How is Node-RED installed? Where is uibuilder installed?
Installed from both pi script and cloned from git; uibuilder installed through palette, latest version. Fresh install from NodeJS/npm/Node-RED/uibuilder from today [date of reporting].

**Comment by TotallyInformation** [comment]
Thanks for this. Can't say I'm surprised. As you say, it is a home-grown solution and that is because I couldn't work out how to get things working the same way as the core nodes do so I just use ACE's built-in full screen option.

So if you manage to get some working code, it would be gratefully received as always :-)

**Comment by TotallyInformation** [comment]
`RED.editor.editText` is defined in `red.js` and simply calls `showTypeEditor` with the type set to `_text`. That pushes a new entry onto the `editStack`

This seems to create a separate ACE edit session for the expanded display. But it doesn't return a useful reference so the only way to detect if a change occurred is to compare the returned text with the value from the main editor.

However, if you then try to set some of the UI using the `fileIsClean(false)` function in the `complete` section of the `editText` function, it doesn't appear to work. You have to do that within the `setTimeout` which delays by 300ms.

That is now all working. Many thanks for the pointers that finally let me fix this one.

Released as v3.0.1
