### ISSUE TITLE
Run uibuilder without node-red admin

### ISSUE THREAD

**Issue by amizer12** [TotallyInformation/node-red-contrib-uibuilder#99]
Hi,
Firstable many thanks for your work!
Im using uibuilder in many projects with great success. 
Quick question, can i run it with node-red admin web interface disabled?
Ideal scenario would be having a web interface on uibuilder and have node red running in background with web admin interface disabled. 
I know workarounds to make it work but was wondering if tjere is a "proper" way to do it..

**Comment by TotallyInformation** [comment]
Hi, uibuilder hasn't been tested without the editor. So I can only suggest giving it a go. In theory it should work once you have set up your flow.

**Comment by amizer12** [comment]
It works indeed !
After adding
`disablkeEditor: true`
to settings.js in node-red home folder - admin web UI is disabled and uibuilder is runnig fine !
Thanks again @TotallyInformation !

**Comment by TotallyInformation** [comment]
Thanks for letting me know.

> run it under root path

Not sure what you mean by that?
